# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structure', '0004_auto_20170216_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='id_code',
            field=models.CharField(max_length=18, unique=True, verbose_name='id'),
        ),
    ]
