# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='Parent',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='codelist',
            name='Codes',
        ),
        migrations.AddField(
            model_name='codelist',
            name='codes',
            field=models.ManyToManyField(to='codelist.Code'),
        ),
    ]
