# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codelist', '0004_auto_20170215_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codelist',
            name='codes',
        ),
        migrations.AddField(
            model_name='code',
            name='codelist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codelist.Codelist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='code',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='isPartial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('codelist', 'id_code')]),
        ),
    ]
