# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelist', '0010_auto_20170228_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_code_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_codelist_annotations_+', to='common.Annotation'),
        ),
    ]
