# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70, null=True), blank=True, null=True, size=None)),
                ('Fax', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70, null=True), blank=True, null=True, size=None)),
                ('X400', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70, null=True), blank=True, null=True, size=None)),
                ('URI', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None)),
                ('Email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=18, null=True)),
                ('Department', models.CharField(blank=True, max_length=18, null=True)),
                ('Role', models.CharField(blank=True, max_length=18, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='organisation.Contact')),
            ],
            options={
                'db_table': 'organisation_contact_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('type_code', models.CharField(blank=True, choices=[(None, 'None'), ('Agency', 'Agency'), ('DataConsumer', 'DataConsumer'), ('DataProvider', 'DataProvider'), ('OrganisationUnit', 'OranisationUnit')], max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_organisation_Annotations_+', to='common.Annotation')),
                ('Contacts', models.ManyToManyField(to='organisation.Contact')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=18, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='organisation.Organisation')),
            ],
            options={
                'db_table': 'organisation_organisation_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='organisationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='contacttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
