# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20170228_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_organisation_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='organisationscheme',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_organisationscheme_annotations_+', to='common.Annotation'),
        ),
    ]
