# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_auto_20170301_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_organisation_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='organisationscheme',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_organisationscheme_annotations_+', to='common.Annotation'),
        ),
    ]
