# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170218_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='AnnotationTitle',
            new_name='annotationTitle',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='AnnotationType',
            new_name='annotationType',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='AnnotationURL',
            new_name='annotationURL',
        ),
        migrations.RenameField(
            model_name='annotationtranslation',
            old_name='AnnotationText',
            new_name='annotationText',
        ),
    ]
