# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_taxonomy', '0015_auto_20170301_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingcategory',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportingcategory_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomy',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportingtaxonomy_annotations_+', to='common.Annotation'),
        ),
    ]
