# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('structure', '0005_auto_20170131_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('version', models.CharField(blank=True, max_length=18, null=True)),
                ('validFrom', models.DateTimeField(blank=True, null=True)),
                ('validTo', models.DateTimeField(blank=True, null=True)),
                ('agencyID', models.CharField(blank=True, max_length=18, null=True)),
                ('isFinal', models.BooleanField(default=False)),
                ('isExternalReference', models.BooleanField(default=False)),
                ('Annotations', models.ManyToManyField(related_name='_metadatastructure_Annotations_+', to='common.Annotation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataStructureComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataStructureTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=18, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='metadata_structure.MetadataStructure')),
            ],
            options={
                'db_table': 'metadata_structure_metadatastructure_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MetadataTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('metadataTarget_type', models.CharField(blank=True, choices=[(None, 'None'), ('KeyDescriptorValuesTarget', 'KeyDescriptorValuesTarget'), ('DataSetTarget', 'DataSetTarget'), ('ConstraintContentTarget', 'ConstraintContentTarget'), ('ReportPeriodTarget', 'ReportPeriodTarget'), ('IdentifiableObjectTarget', 'IdentifiableObjectTarget')], max_length=18, null=True)),
                ('objectType', models.CharField(blank=True, choices=[(None, 'None'), ('Any', 'Any'), ('Agency', 'Agency'), ('AgencyScheme', 'AgencyScheme'), ('AttachmentConstraint', 'AttachmentConstraint'), ('Attribute', 'Attribute'), ('AttributeDescriptor', 'AttributeDescriptor'), ('Categorisation', 'Categorisation'), ('Category', 'Category'), ('CategorySchemeMap', 'CategorySchemeMap'), ('CategoryScheme', 'CategoryScheme'), ('Code', 'Code'), ('CodeMap', 'CodeMap'), ('Codelist', 'Codelist'), ('CodelistMap', 'CodelistMap'), ('ComponentMap', 'ComponentMap'), ('Concept', 'Concept'), ('ConceptMap', 'ConceptMap'), ('ConceptScheme', 'ConceptScheme'), ('ConceptSchemeMap', 'ConceptSchemeMap'), ('Constraint', 'Constraint'), ('ConstraintTarget', 'ConstraintTarget'), ('ContentConstraint', 'ContentConstraint'), ('Dataflow', 'Dataflow'), ('DataConsumer', 'DataConsumer'), ('DataConsumerScheme', 'DataConsumerScheme'), ('DataProvider', 'DataProvider'), ('DataProviderScheme', 'DataProviderScheme'), ('DataSetTarget', 'DataSetTarget'), ('DataStructure', 'DataStructure'), ('Dimension', 'Dimension'), ('DimensionDescriptor', 'DimensionDescriptor'), ('DimensionDescriptorValuesTarget', 'DimensionDescriptorValuesTarget'), ('GroupDimensionDescriptor', 'GroupDimensionDescriptor'), ('HierarchicalCode', 'HierarchicalCode'), ('HierarchicalCodelist', 'HierarchicalCodelist'), ('Hierarchy', 'Hierarchy'), ('HybridCodelistMap', 'HybridCodelistMap'), ('HybridCodeMap', 'HybridCodeMap'), ('IdentifiableObjectTarget', 'IdentifiableObjectTarget'), ('Level', 'Level'), ('MeasureDescriptor', 'MeasureDescriptor'), ('MeasureDimension', 'MeasureDimension'), ('Metadataflow', 'Metadataflow'), ('MetadataAttribute', 'MetadataAttribute'), ('MetadataSet', 'MetadataSet'), ('MetadataStructure', 'MetadataStructure'), ('MetadataTarget', 'MetadataTarget'), ('Organisation', 'Organisation'), ('OrganisationMap', 'OrganisationMap'), ('OrganisationScheme', 'OrganisationScheme'), ('OrganisationSchemeMap', 'OrganisationSchemeMap'), ('OrganisationUnit', 'OrganisationUnit'), ('OrganisationUnitScheme', 'OrganisationUnitScheme'), ('PrimaryMeasure', 'PrimaryMeasure'), ('Process', 'Process'), ('ProcessStep', 'ProcessStep'), ('ProvisionAgreement', 'ProvisionAgreement'), ('ReportingCategory', 'ReportingCategory'), ('ReportingCategoryMap', 'ReportingCategoryMap'), ('ReportingTaxonomy', 'ReportingTaxonomy'), ('ReportingTaxonomyMap', 'ReportingTaxonomyMap'), ('ReportingYearStartDay', 'ReportingYearStartDay'), ('ReportPeriodTarget', 'ReportPeriodTarget'), ('ReportStructure', 'ReportStructure'), ('StructureMap', 'StructureMap'), ('StructureSet', 'StructureSet'), ('TimeDimension', 'TimeDimension'), ('Transition', 'Transition')], max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_metadatatarget_Annotations_+', to='common.Annotation')),
                ('LocalRepresentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Representation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_metadatatargetlist_Annotations_+', to='common.Annotation')),
                ('MetadataTargetList', models.ManyToManyField(related_name='_metadatatargetlist_MetadataTargetList_+', to='metadata_structure.MetadataTarget')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTargetListTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='metadata_structure.MetadataTargetList')),
            ],
            options={
                'db_table': 'metadata_structure_metadatatargetlist_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MetadataTargetTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='metadata_structure.MetadataTarget')),
            ],
            options={
                'db_table': 'metadata_structure_metadatatarget_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReportStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('minOccurs', models.IntegerField(blank=True, null=True)),
                ('maxOccurs', models.IntegerField(blank=True, null=True)),
                ('isPresentational', models.NullBooleanField()),
                ('Annotations', models.ManyToManyField(related_name='_reportstructure_Annotations_+', to='common.Annotation')),
                ('ConceptIdentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.Reference')),
                ('LocalRepresentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Representation')),
                ('MetadataAttributes', models.ManyToManyField(related_name='_reportstructure_MetadataAttributes_+', to='metadata_structure.ReportStructure')),
                ('MetadataTargets', models.ManyToManyField(related_name='_reportstructure_MetadataTargets_+', to='common.Reference')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportStructureList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_reportstructurelist_Annotations_+', to='common.Annotation')),
                ('ReportStructureList', models.ManyToManyField(related_name='_reportstructurelist_ReportStructureList_+', to='metadata_structure.ReportStructure')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportStructureListTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='metadata_structure.ReportStructureList')),
            ],
            options={
                'db_table': 'metadata_structure_reportstructurelist_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReportStructureTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='metadata_structure.ReportStructure')),
            ],
            options={
                'db_table': 'metadata_structure_reportstructure_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='metadatastructurecomponents',
            name='MetadataTargets',
            field=models.ManyToManyField(related_name='_metadatastructurecomponents_MetadataTargets_+', to='metadata_structure.MetadataTargetList'),
        ),
        migrations.AddField(
            model_name='metadatastructurecomponents',
            name='ReportStructures',
            field=models.ManyToManyField(related_name='_metadatastructurecomponents_ReportStructures_+', to='metadata_structure.ReportStructureList'),
        ),
        migrations.AddField(
            model_name='metadatastructure',
            name='MetadataStructureComponents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metadata_structure.MetadataStructureComponents'),
        ),
        migrations.AlterUniqueTogether(
            name='reportstructuretranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='reportstructurelisttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='metadatatargettranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='metadatatargetlisttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='metadatastructuretranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
