# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170225_1123'),
        ('metadata_structure', '0006_auto_20170225_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatastructuretranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='metadatastructure',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='metadatatarget',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='metadatatargetlist',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='reportstructure',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='reportstructurelist',
            name='Annotations',
        ),
        migrations.AddField(
            model_name='metadatastructure',
            name='annotations',
            field=models.ManyToManyField(related_name='_metadatastructure_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='metadatastructuretranslation',
            name='name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='metadatatarget',
            name='annotations',
            field=models.ManyToManyField(related_name='_metadatatarget_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='metadatatargetlist',
            name='annotations',
            field=models.ManyToManyField(related_name='_metadatatargetlist_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='reportstructure',
            name='annotations',
            field=models.ManyToManyField(related_name='_reportstructure_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='reportstructurelist',
            name='annotations',
            field=models.ManyToManyField(related_name='_reportstructurelist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='metadatastructure',
            name='id_code',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
    ]
