# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_structure', '0013_auto_20170228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatastructure',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_metadatastructure_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='metadatatarget',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_metadatatarget_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='metadatatargetlist',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_metadatatargetlist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='reportstructure',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportstructure_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='reportstructurelist',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportstructurelist_annotations_+', to='common.Annotation'),
        ),
    ]
