# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localID', models.CharField(blank=True, max_length=18, null=True)),
                ('softwarePackage', models.CharField(blank=True, max_length=18, null=True)),
                ('softwareLanguage', models.CharField(blank=True, max_length=18, null=True)),
                ('softwareVersion', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_computation_Annotations_+', to='common.Annotation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ComputationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tranaslations', to='process.Computation')),
            ],
            options={
                'db_table': 'process_computation_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InputOutpout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localID', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_inputoutpout_Annotations_+', to='common.Annotation')),
                ('ObjectType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Reference')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InputOutpoutTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='process.InputOutpout')),
            ],
            options={
                'db_table': 'process_inputoutpout_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('version', models.CharField(blank=True, max_length=18, null=True)),
                ('validFrom', models.DateTimeField(blank=True, null=True)),
                ('validTo', models.DateTimeField(blank=True, null=True)),
                ('agencyID', models.CharField(blank=True, max_length=18, null=True)),
                ('isFinal', models.BooleanField(default=False)),
                ('isExternalReference', models.BooleanField(default=False)),
                ('Annotations', models.ManyToManyField(related_name='_process_Annotations_+', to='common.Annotation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_processstep_Annotations_+', to='common.Annotation')),
                ('Computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='process.Computation')),
                ('Input', models.ManyToManyField(related_name='_processstep_Input_+', to='process.InputOutpout')),
                ('Outpout', models.ManyToManyField(related_name='_processstep_Outpout_+', to='process.InputOutpout')),
                ('ProcessSteps', models.ManyToManyField(related_name='_processstep_ProcessSteps_+', to='process.ProcessStep')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStepTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=18, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='process.ProcessStep')),
            ],
            options={
                'db_table': 'process_processstep_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcessTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=18, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='process.Process')),
            ],
            options={
                'db_table': 'process_process_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('localID', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_transition_Annotations_+', to='common.Annotation')),
                ('Conditions', models.ManyToManyField(related_name='_transition_Conditions_+', to='common.Text')),
                ('TargetStep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.Reference')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TransitionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='process.Transition')),
            ],
            options={
                'db_table': 'process_transition_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='processstep',
            name='Transitions',
            field=models.ManyToManyField(related_name='_processstep_Transitions_+', to='process.Transition'),
        ),
        migrations.AddField(
            model_name='process',
            name='ProcessSteps',
            field=models.ManyToManyField(related_name='_process_ProcessSteps_+', to='process.ProcessStep'),
        ),
        migrations.AlterUniqueTogether(
            name='transitiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='processtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='processsteptranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='inputoutpouttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='computationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
