# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170225_1123'),
        ('process', '0006_auto_20170225_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processsteptranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='processsteptranslation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='processtranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='computation',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='inputoutpout',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='process',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='Annotations',
        ),
        migrations.AddField(
            model_name='computation',
            name='annotations',
            field=models.ManyToManyField(related_name='_computation_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='inputoutpout',
            name='annotations',
            field=models.ManyToManyField(related_name='_inputoutpout_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='process',
            name='annotations',
            field=models.ManyToManyField(related_name='_process_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='annotations',
            field=models.ManyToManyField(related_name='_processstep_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='processtranslation',
            name='name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='annotations',
            field=models.ManyToManyField(related_name='_transition_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id_code',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
    ]
