# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20170228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computation',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_computation_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='inputoutpout',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_inputoutpout_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='process',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_process_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_processstep_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_transition_annotations_+', to='common.Annotation'),
        ),
    ]
