# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20170228_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryschemetranslation',
            name='Name',
        ),
        migrations.AlterField(
            model_name='categoryschemetranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
