# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20170228_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryscheme',
            name='isPartial',
        ),
    ]
