# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_auto_20170301_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_category_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='categoryscheme',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_categoryscheme_annotations_+', to='common.Annotation'),
        ),
    ]
