# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170225_1123'),
        ('hierarchical_codelist', '0006_auto_20170225_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hierarchicalcodelisttranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hierarchytranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hierarchytranslation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='leveltranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='leveltranslation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hierarchicalcode',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='hierarchicalcodelist',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='level',
            name='Annotations',
        ),
        migrations.AddField(
            model_name='hierarchicalcode',
            name='annotations',
            field=models.ManyToManyField(related_name='_hierarchicalcode_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='hierarchicalcodelist',
            name='annotations',
            field=models.ManyToManyField(related_name='_hierarchicalcodelist_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='hierarchicalcodelisttranslation',
            name='name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='annotations',
            field=models.ManyToManyField(related_name='_hierarchy_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='level',
            name='annotations',
            field=models.ManyToManyField(related_name='_level_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='hierarchicalcodelist',
            name='id_code',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
    ]
