# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical_codelist', '0010_auto_20170228_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchicalcode',
            name='urn',
        ),
        migrations.RemoveField(
            model_name='hierarchicalcodelist',
            name='isExternalReference',
        ),
        migrations.RemoveField(
            model_name='hierarchicalcodelist',
            name='urn',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='urn',
        ),
        migrations.RemoveField(
            model_name='level',
            name='urn',
        ),
        migrations.AlterField(
            model_name='hierarchicalcode',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_hierarchicalcode_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='hierarchicalcodelist',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_hierarchicalcodelist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_hierarchy_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='level',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_level_annotations_+', to='common.Annotation'),
        ),
    ]
