# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170225_1123'),
        ('metadataflow', '0006_auto_20170225_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataflowtranslation',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='metadataflowtranslation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='metadataflow',
            name='Annotations',
        ),
        migrations.AddField(
            model_name='metadataflow',
            name='annotations',
            field=models.ManyToManyField(related_name='_metadataflow_annotations_+', to='common.Annotation'),
        ),
    ]
