# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0004_auto_20170215_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflow',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='dataflow',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataflow',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
