# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0002_auto_20170215_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintartefact',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='constraintartefact',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
    ]
