# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0009_auto_20170228_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_concept_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='conceptscheme',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_conceptscheme_annotations_+', to='common.Annotation'),
        ),
    ]
