# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_set', '0002_auto_20170215_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
    ]
