# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_set', '0003_auto_20170215_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='agencyID',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='isExternalReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='validFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='validTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='version',
            field=models.CharField(default='1.0', max_length=18),
        ),
    ]
