# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_set', '0011_auto_20170228_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='categoryschememaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='codelistmaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='codemaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='componentmaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='conceptmaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='conceptschememaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='hybridcodemaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='organisationmaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='organisationschememaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='reportingcategorymaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='reportingtaxonomymaptranslation',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='structuresettranslation',
            name='Name',
        ),
        migrations.AlterField(
            model_name='categorymaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryschememaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codelistmaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codemaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentmaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptmaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptschememaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hybridcodemaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationmaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationschememaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportingcategorymaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymaptranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structuresettranslation',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
