# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_set', '0013_auto_20170228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_categorymap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='categoryschememap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_categoryschememap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='codelistmap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_codelistmap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='codemap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_codemap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='componentmap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_componentmap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='conceptmap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_conceptmap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='conceptschememap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_conceptschememap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='hybridcodelistmap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_hybridcodelistmap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='hybridcodemap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_hybridcodemap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='organisationmap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_organisationmap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='organisationschememap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_organisationschememap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='reportingcategorymap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportingcategorymap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='reportingtaxonomymap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_reportingtaxonomymap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='structuremap',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_structuremap_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='structureset',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_structureset_annotations_+', to='common.Annotation'),
        ),
    ]
