# MAX_LENGTH = {
#     'id': 18,
#     'name': 70,
# }

ORGANISATION_TYPES = (
    (None, 'None'),
    ('Agency', 'Agency'),
    ('DataConsumer', 'DataConsumer'),
    ('DataProvider', 'DataProvider'),
    ('OrganisationUnit', 'OranisationUnit'),
)

DIMENSION_TYPES = (
    ("dimension", "dimension"),
    ("measureDimension", "measureDimension")
)

OBJECT_TYPES = (
    (None, 'None'),
    ("Any", "Any"),
    ("Agency", "Agency"),
    ("AgencyScheme", "AgencyScheme"),
    ("AttachmentConstraint", "AttachmentConstraint"),
    ("Attribute", "Attribute"),
    ("AttributeDescriptor", "AttributeDescriptor"),
    ("Categorisation", "Categorisation"),
    ("Category", "Category"),
    ("CategorySchemeMap", "CategorySchemeMap"),
    ("CategoryScheme", "CategoryScheme"),
    ("Code", "Code"),
    ("CodeMap", "CodeMap"),
    ("Codelist", "Codelist"),
    ("CodelistMap", "CodelistMap"),
    ("ComponentMap", "ComponentMap"),
    ("Concept", "Concept"),
    ("ConceptMap", "ConceptMap"),
    ("ConceptScheme", "ConceptScheme"),
    ("ConceptSchemeMap", "ConceptSchemeMap"),
    ("Constraint", "Constraint"),
    ("ConstraintTarget", "ConstraintTarget"),
    ("ContentConstraint", "ContentConstraint"),
    ("Dataflow", "Dataflow"),
    ("DataConsumer", "DataConsumer"),
    ("DataConsumerScheme", "DataConsumerScheme"),
    ("DataProvider", "DataProvider"),
    ("DataProviderScheme", "DataProviderScheme"),
    ("DataSetTarget", "DataSetTarget"),
    ("DataStructure", "DataStructure"),
    ("Dimension", "Dimension"),
    ("DimensionDescriptor", "DimensionDescriptor"),
    ("DimensionDescriptorValuesTarget", "DimensionDescriptorValuesTarget"),
    ("GroupDimensionDescriptor", "GroupDimensionDescriptor"),
    ("HierarchicalCode", "HierarchicalCode"),
    ("HierarchicalCodelist", "HierarchicalCodelist"),
    ("Hierarchy", "Hierarchy"),
    ("HybridCodelistMap", "HybridCodelistMap"),
    ("HybridCodeMap", "HybridCodeMap"),
    ("IdentifiableObjectTarget", "IdentifiableObjectTarget"),
    ("Level", "Level"),
    ("MeasureDescriptor", "MeasureDescriptor"),
    ("MeasureDimension", "MeasureDimension"),
    ("Metadataflow", "Metadataflow"),
    ("MetadataAttribute", "MetadataAttribute"),
    ("MetadataSet", "MetadataSet"),
    ("MetadataStructure", "MetadataStructure"),
    ("MetadataTarget", "MetadataTarget"),
    ("Organisation", "Organisation"),
    ("OrganisationMap", "OrganisationMap"),
    ("OrganisationScheme", "OrganisationScheme"),
    ("OrganisationSchemeMap", "OrganisationSchemeMap"),
    ("OrganisationUnit", "OrganisationUnit"),
    ("OrganisationUnitScheme", "OrganisationUnitScheme"),
    ("PrimaryMeasure", "PrimaryMeasure"),
    ("Process", "Process"),
    ("ProcessStep", "ProcessStep"),
    ("ProvisionAgreement", "ProvisionAgreement"),
    ("ReportingCategory", "ReportingCategory"),
    ("ReportingCategoryMap", "ReportingCategoryMap"),
    ("ReportingTaxonomy", "ReportingTaxonomy"),
    ("ReportingTaxonomyMap", "ReportingTaxonomyMap"),
    ("ReportingYearStartDay", "ReportingYearStartDay"),
    ("ReportPeriodTarget", "ReportPeriodTarget"),
    ("ReportStructure", "ReportStructure"),
    ("StructureMap", "StructureMap"),
    ("StructureSet", "StructureSet"),
    ("TimeDimension", "TimeDimension"),
    ("Transition", "Transition"),
)

METADATA_TARGET_TYPES = (
    (None, 'None'),
    ('KeyDescriptorValuesTarget', 'KeyDescriptorValuesTarget'),
    ('DataSetTarget', 'DataSetTarget'),
    ('ConstraintContentTarget', 'ConstraintContentTarget'),
    ('ReportPeriodTarget', 'ReportPeriodTarget'),
    ('IdentifiableObjectTarget', 'IdentifiableObjectTarget'),
)

DATA_TYPES = ( 
    (None, 'None'),
    ('String', 'String'),
    ('Alpha', 'Alpha'),
    ('AlphaNumeric', 'AlphaNumeric'),
    ('Numeric', 'Numeric'),
    ('BigInteger', 'BigInteger'),
    ('Integer', 'Integer'),
    ('Long', 'Long'),
    ('Short', 'Short'),
    ('Decimal', 'Decimal'),
    ('Float', 'Float'),
    ('Double', 'Double'),
    ('Boolean', 'Boolean'),
    ('URI', 'URI'),
    ('Count', 'Count'),
    ('InclusiveValueRange', 'InclusiveValueRange'),
    ('ExclusiveValueRange', 'ExclusiveValueRange'),
    ('Incremental', 'Incremental'),
    ('ObservationalTimePeriod', 'ObservationalTimePeriod'),
    ('StandardTimePeriod', 'StandardTimePeriod'),
    ('BasicTimePeriod', 'BasicTimePeriod'),
    ('GregorianTimePeriod', 'GregorianTimePeriod'),
    ('GregorianYear', 'GregorianYear'),
    ('GregorianYearMonth', 'GregorianYearMonth'),
    ('GregorianDay', 'GregorianDay'),
    ('ReportingTimePeriod', 'ReportingTimePeriod'),
    ('ReportingYear', 'ReportingYear'),
    ('ReportingSemester', 'ReportingSemester'),
    ('ReportingTrimester', 'ReportingTrimester'),
    ('ReportingQuarter', 'ReportingQuarter'),
    ('ReportingMonth', 'ReportingMonth'),
    ('ReportingWeek', 'ReportingWeek'),
    ('ReportingDay', 'ReportingDay'),
    ('DateTime', 'DateTime'),
    ('TimeRange', 'TimeRange'),
    ('Month', 'Month'),
    ('MonthDay', 'MonthDay'),
    ('Day', 'Day'),
    ('Time', 'Time'),
    ('Duration', 'Duration'),
    ('XHTML', 'XHTML'),
    ('KeyValues', 'KeyValues'),
    ('IdentifiableReference', 'IdentifiableReference'),
    ('DataSetReference', 'DataSetReference'),
    ('AttachmentConstraintReference', 'AttachmentConstraintReference'),
)


CLASS_TYPES = (
    (None, 'None'),
    ("Any", "Any"),
    ("Agency", "Agency"),
    ("AgencyScheme", "AgencyScheme"),
    ("AttachmentConstraint", "AttachmentConstraint"),
    ("Attribute", "Attribute"),
    ("AttributeDescriptor", "AttributeDescriptor"),
    ("Categorisation", "Categorisation"),
    ("Category", "Category"),
    ("CategorySchemeMap", "CategorySchemeMap"),
    ("CategoryScheme", "CategoryScheme"),
    ("Code", "Code"),
    ("CodeMap", "CodeMap"),
    ("Codelist", "Codelist"),
    ("CodelistMap", "CodelistMap"),
    ("ComponentMap", "ComponentMap"),
    ("Concept", "Concept"),
    ("ConceptMap", "ConceptMap"),
    ("ConceptScheme", "ConceptScheme"),
    ("ConceptSchemeMap", "ConceptSchemeMap"),
    ("Constraint", "Constraint"),
    ("ConstraintTarget", "ConstraintTarget"),
    ("ContentConstraint", "ContentConstraint"),
    ("Dataflow", "Dataflow"),
    ("DataConsumer", "DataConsumer"),
    ("DataConsumerScheme", "DataConsumerScheme"),
    ("DataProvider", "DataProvider"),
    ("DataProviderScheme", "DataProviderScheme"),
    ("DataSetTarget", "DataSetTarget"),
    ("DataStructure", "DataStructure"),
    ("Dimension", "Dimension"),
    ("DimensionDescriptor", "DimensionDescriptor"),
    ("DimensionDescriptorValuesTarget", "DimensionDescriptorValuesTarget"),
    ("GroupDimensionDescriptor", "GroupDimensionDescriptor"),
    ("HierarchicalCode", "HierarchicalCode"),
    ("HierarchicalCodelist", "HierarchicalCodelist"),
    ("Hierarchy", "Hierarchy"),
    ("HybridCodelistMap", "HybridCodelistMap"),
    ("HybridCodeMap", "HybridCodeMap"),
    ("IdentifiableObjectTarget", "IdentifiableObjectTarget"),
    ("Level", "Level"),
    ("MeasureDescriptor", "MeasureDescriptor"),
    ("MeasureDimension", "MeasureDimension"),
    ("Metadataflow", "Metadataflow"),
    ("MetadataAttribute", "MetadataAttribute"),
    ("MetadataSet", "MetadataSet"),
    ("MetadataStructure", "MetadataStructure"),
    ("MetadataTarget", "MetadataTarget"),
    ("Organisation", "Organisation"),
    ("OrganisationMap", "OrganisationMap"),
    ("OrganisationScheme", "OrganisationScheme"),
    ("OrganisationSchemeMap", "OrganisationSchemeMap"),
    ("OrganisationUnit", "OrganisationUnit"),
    ("OrganisationUnitScheme", "OrganisationUnitScheme"),
    ("PrimaryMeasure", "PrimaryMeasure"),
    ("Process", "Process"),
    ("ProcessStep", "ProcessStep"),
    ("ProvisionAgreement", "ProvisionAgreement"),
    ("ReportingCategory", "ReportingCategory"),
    ("ReportingCategoryMap", "ReportingCategoryMap"),
    ("ReportingTaxonomy", "ReportingTaxonomy"),
    ("ReportingTaxonomyMap", "ReportingTaxonomyMap"),
    ("ReportingYearStartDay", "ReportingYearStartDay"),
    ("ReportPeriodTarget", "ReportPeriodTarget"),
    ("ReportStructure", "ReportStructure"),
    ("StructureMap", "StructureMap"),
    ("StructureSet", "StructureSet"),
    ("TimeDimension", "TimeDimension"),
    ("Transition", "Transition"),
)

PACKAGE_TYPES = (
    (None, 'None'),
    ("base", "base"),
    ("datastructure", "datastructure"),
    ("metadatastructure", "metadatastructure"),
    ("process", "process"),
    ("registry", "registry"),
    ("mapping", "mapping"),
    ("codelist", "codelist"),
    ("categoryscheme", "categoryscheme"),
    ("conceptscheme", "conceptscheme"),
)

DIMENSION_TYPES =(
    ('dimension', 'Dimension'),
    ('time', 'TimeDimension'),
    ('measure', 'MeasureDimension')
)

METATDATA_TARGET_COMPONENTS = (
    ('DIMENSION_DESCRIPTOR_VALUES_TARGET', 'KeyDescriptorValuesTarget'),
    ('DATA_SET_TARGET', 'DataSetTarget'),
    ('CONSTRAINT_CONTENT_TARGET', 'ConstraintContentTarget'),
    ('REPORT_PERIOD_TARGET', 'ReportPeriodTarget'),
    ('IDENTIFIABLE_OBJECT_TARGET', 'IdentifiableObjectTarget')
)

TOKENS = (
    ('Value', 'Value'),
    ('Name', 'Name'),
    ('Desription', 'Description')
)

ACTIONS = (
    ('A', 'Append'),
    ('R', 'Replace'),
    ('D', 'Delete'),
)
