# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('dimension_type', models.CharField(blank=True, choices=[('dimension', 'dimenstion'), ('measureDimension', 'measureDimension')], max_length=18, null=True)),
                ('objectType', models.CharField(blank=True, choices=[(None, 'None'), ('Any', 'Any'), ('Agency', 'Agency'), ('AgencyScheme', 'AgencyScheme'), ('AttachmentConstraint', 'AttachmentConstraint'), ('Attribute', 'Attribute'), ('AttributeDescriptor', 'AttributeDescriptor'), ('Categorisation', 'Categorisation'), ('Category', 'Category'), ('CategorySchemeMap', 'CategorySchemeMap'), ('CategoryScheme', 'CategoryScheme'), ('Code', 'Code'), ('CodeMap', 'CodeMap'), ('Codelist', 'Codelist'), ('CodelistMap', 'CodelistMap'), ('ComponentMap', 'ComponentMap'), ('Concept', 'Concept'), ('ConceptMap', 'ConceptMap'), ('ConceptScheme', 'ConceptScheme'), ('ConceptSchemeMap', 'ConceptSchemeMap'), ('Constraint', 'Constraint'), ('ConstraintTarget', 'ConstraintTarget'), ('ContentConstraint', 'ContentConstraint'), ('Dataflow', 'Dataflow'), ('DataConsumer', 'DataConsumer'), ('DataConsumerScheme', 'DataConsumerScheme'), ('DataProvider', 'DataProvider'), ('DataProviderScheme', 'DataProviderScheme'), ('DataSetTarget', 'DataSetTarget'), ('DataStructure', 'DataStructure'), ('Dimension', 'Dimension'), ('DimensionDescriptor', 'DimensionDescriptor'), ('DimensionDescriptorValuesTarget', 'DimensionDescriptorValuesTarget'), ('GroupDimensionDescriptor', 'GroupDimensionDescriptor'), ('HierarchicalCode', 'HierarchicalCode'), ('HierarchicalCodelist', 'HierarchicalCodelist'), ('Hierarchy', 'Hierarchy'), ('HybridCodelistMap', 'HybridCodelistMap'), ('HybridCodeMap', 'HybridCodeMap'), ('IdentifiableObjectTarget', 'IdentifiableObjectTarget'), ('Level', 'Level'), ('MeasureDescriptor', 'MeasureDescriptor'), ('MeasureDimension', 'MeasureDimension'), ('Metadataflow', 'Metadataflow'), ('MetadataAttribute', 'MetadataAttribute'), ('MetadataSet', 'MetadataSet'), ('MetadataStructure', 'MetadataStructure'), ('MetadataTarget', 'MetadataTarget'), ('Organisation', 'Organisation'), ('OrganisationMap', 'OrganisationMap'), ('OrganisationScheme', 'OrganisationScheme'), ('OrganisationSchemeMap', 'OrganisationSchemeMap'), ('OrganisationUnit', 'OrganisationUnit'), ('OrganisationUnitScheme', 'OrganisationUnitScheme'), ('PrimaryMeasure', 'PrimaryMeasure'), ('Process', 'Process'), ('ProcessStep', 'ProcessStep'), ('ProvisionAgreement', 'ProvisionAgreement'), ('ReportingCategory', 'ReportingCategory'), ('ReportingCategoryMap', 'ReportingCategoryMap'), ('ReportingTaxonomy', 'ReportingTaxonomy'), ('ReportingTaxonomyMap', 'ReportingTaxonomyMap'), ('ReportingYearStartDay', 'ReportingYearStartDay'), ('ReportPeriodTarget', 'ReportPeriodTarget'), ('ReportStructure', 'ReportStructure'), ('StructureMap', 'StructureMap'), ('StructureSet', 'StructureSet'), ('TimeDimension', 'TimeDimension'), ('Transition', 'Transition')], max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_component_Annotations_+', to='common.Annotation')),
                ('AttachmentConstraint', models.ManyToManyField(related_name='_component_AttachmentConstraint_+', to='common.Reference')),
                ('ConceptIdentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.Reference')),
                ('ConceptRole', models.ManyToManyField(related_name='_component_ConceptRole_+', to='common.Reference')),
                ('GroupDimensions', models.ManyToManyField(related_name='_component_GroupDimensions_+', to='common.Reference')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.URLField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('id_code', models.CharField(blank=True, max_length=18, null=True)),
                ('Annotations', models.ManyToManyField(related_name='_componentlist_Annotations_+', to='common.Annotation')),
                ('Components', models.ManyToManyField(related_name='_componentlist_Components_+', to='structure.Component')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentListTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='structure.ComponentList')),
            ],
            options={
                'db_table': 'structure_componentlist_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComponentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='structure.Component')),
            ],
            options={
                'db_table': 'structure_component_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumeration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='TextFormatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textType', models.CharField(blank=True, choices=[('String', 'String'), ('Boolean', 'Boolean'), ('Double', 'Double'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Incremental', 'Incremental'), ('ReportingYear', 'ReportingYear'), ('Decimal', 'Decimal'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Short', 'Short'), ('ReportingSemester', 'ReportingSemester'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('DataSetReference', 'DataSetReference'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), (None, 'None'), ('TimeRange', 'TimeRange'), ('Month', 'Month'), ('KeyValues', 'KeyValues'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Count', 'Count'), ('ReportingWeek', 'ReportingWeek'), ('IdentifiableReference', 'IdentifiableReference'), ('Integer', 'Integer'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('URI', 'URI'), ('ReportingDay', 'ReportingDay'), ('GregorianYear', 'GregorianYear'), ('Day', 'Day'), ('Time', 'Time'), ('ReportingMonth', 'ReportingMonth'), ('Alpha', 'Alpha'), ('BigInteger', 'BigInteger'), ('Numeric', 'Numeric'), ('Long', 'Long'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('DateTime', 'DateTime'), ('GregorianYearMonth', 'GregorianYearMonth'), ('MonthDay', 'MonthDay'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Float', 'Float')], max_length=18, null=True)),
                ('isSequence', models.NullBooleanField()),
                ('interval', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('startValue', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('endValue', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('timeInterval', models.DurationField(blank=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('minLength', models.PositiveIntegerField(blank=True, null=True)),
                ('maxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('minValue', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('maxValue', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('decimals', models.PositiveIntegerField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('isMultiLingual', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='representation',
            name='EnumerationFormat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='representation',
            name='TextFormat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='component',
            name='LocalRepresentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Representation'),
        ),
        migrations.AlterUniqueTogether(
            name='componenttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='componentlisttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
