# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Alpha', 'Alpha'), ('Numeric', 'Numeric'), ('String', 'String'), ('Short', 'Short'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingMonth', 'ReportingMonth'), ('AlphaNumeric', 'AlphaNumeric'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('Month', 'Month'), ('Time', 'Time'), ('Integer', 'Integer'), ('Float', 'Float'), ('Count', 'Count'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingWeek', 'ReportingWeek'), ('MonthDay', 'MonthDay'), ('URI', 'URI'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('GregorianYear', 'GregorianYear'), ('TimeRange', 'TimeRange'), ('GregorianDay', 'GregorianDay'), ('XHTML', 'XHTML'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Incremental', 'Incremental'), ('GregorianYearMonth', 'GregorianYearMonth'), ('DataSetReference', 'DataSetReference'), ('Duration', 'Duration'), (None, 'None'), ('Long', 'Long'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Day', 'Day'), ('KeyValues', 'KeyValues'), ('Decimal', 'Decimal'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ReportingYear', 'ReportingYear'), ('IdentifiableReference', 'IdentifiableReference'), ('BasicTimePeriod', 'BasicTimePeriod'), ('DateTime', 'DateTime'), ('BigInteger', 'BigInteger'), ('Double', 'Double'), ('Boolean', 'Boolean')], max_length=255, null=True),
        ),
    ]
