# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20170628_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('GregorianTimePeriod', 'GregorianTimePeriod'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Float', 'Float'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('BigInteger', 'BigInteger'), ('ReportingWeek', 'ReportingWeek'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingYear', 'ReportingYear'), ('Time', 'Time'), ('IdentifiableReference', 'IdentifiableReference'), ('ReportingMonth', 'ReportingMonth'), ('AlphaNumeric', 'AlphaNumeric'), ('URI', 'URI'), ('GregorianDay', 'GregorianDay'), ('TimeRange', 'TimeRange'), ('Day', 'Day'), ('XHTML', 'XHTML'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Duration', 'Duration'), ('ReportingDay', 'ReportingDay'), ('DataSetReference', 'DataSetReference'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ExclusiveValueRange', 'ExclusiveValueRange'), (None, 'None'), ('MonthDay', 'MonthDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Long', 'Long'), ('Incremental', 'Incremental'), ('Month', 'Month'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Short', 'Short'), ('String', 'String'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('Alpha', 'Alpha'), ('Boolean', 'Boolean'), ('Decimal', 'Decimal'), ('KeyValues', 'KeyValues'), ('DateTime', 'DateTime'), ('BasicTimePeriod', 'BasicTimePeriod')], max_length=255, null=True),
        ),
    ]
