# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20170131_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('URI', 'URI'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Incremental', 'Incremental'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingYear', 'ReportingYear'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('DateTime', 'DateTime'), ('Count', 'Count'), ('Time', 'Time'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ReportingQuarter', 'ReportingQuarter'), ('Short', 'Short'), ('Boolean', 'Boolean'), ('GregorianYear', 'GregorianYear'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('GregorianYearMonth', 'GregorianYearMonth'), ('KeyValues', 'KeyValues'), ('IdentifiableReference', 'IdentifiableReference'), ('Integer', 'Integer'), ('AlphaNumeric', 'AlphaNumeric'), ('Alpha', 'Alpha'), (None, 'None'), ('DataSetReference', 'DataSetReference'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Numeric', 'Numeric'), ('Long', 'Long'), ('Month', 'Month'), ('Day', 'Day'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('TimeRange', 'TimeRange'), ('XHTML', 'XHTML'), ('Duration', 'Duration'), ('MonthDay', 'MonthDay'), ('BigInteger', 'BigInteger'), ('Float', 'Float'), ('ReportingWeek', 'ReportingWeek'), ('ReportingDay', 'ReportingDay'), ('String', 'String')], max_length=18, null=True),
        ),
    ]
