# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20170131_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Float', 'Float'), ('Count', 'Count'), ('Numeric', 'Numeric'), ('BigInteger', 'BigInteger'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('KeyValues', 'KeyValues'), ('Boolean', 'Boolean'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('String', 'String'), ('Day', 'Day'), ('Time', 'Time'), ('Integer', 'Integer'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingYear', 'ReportingYear'), ('ReportingWeek', 'ReportingWeek'), ('GregorianYear', 'GregorianYear'), ('Month', 'Month'), ('ReportingSemester', 'ReportingSemester'), ('TimeRange', 'TimeRange'), ('AlphaNumeric', 'AlphaNumeric'), ('ReportingDay', 'ReportingDay'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('InclusiveValueRange', 'InclusiveValueRange'), ('DataSetReference', 'DataSetReference'), ('Long', 'Long'), ('URI', 'URI'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('Duration', 'Duration'), ('Decimal', 'Decimal'), ('GregorianDay', 'GregorianDay'), ('Double', 'Double'), ('Incremental', 'Incremental'), ('ReportingMonth', 'ReportingMonth'), ('IdentifiableReference', 'IdentifiableReference'), ('DateTime', 'DateTime'), ('MonthDay', 'MonthDay'), ('XHTML', 'XHTML'), ('Short', 'Short'), ('Alpha', 'Alpha')], max_length=18, null=True),
        ),
    ]
