# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_auto_20170131_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('ReportingSemester', 'ReportingSemester'), ('GregorianYearMonth', 'GregorianYearMonth'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Integer', 'Integer'), ('Short', 'Short'), (None, 'None'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('ReportingWeek', 'ReportingWeek'), ('DateTime', 'DateTime'), ('MonthDay', 'MonthDay'), ('TimeRange', 'TimeRange'), ('Long', 'Long'), ('Day', 'Day'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('IdentifiableReference', 'IdentifiableReference'), ('DataSetReference', 'DataSetReference'), ('Incremental', 'Incremental'), ('GregorianDay', 'GregorianDay'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingYear', 'ReportingYear'), ('KeyValues', 'KeyValues'), ('Month', 'Month'), ('GregorianYear', 'GregorianYear'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('AlphaNumeric', 'AlphaNumeric'), ('Alpha', 'Alpha'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('String', 'String'), ('Count', 'Count'), ('BigInteger', 'BigInteger'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingMonth', 'ReportingMonth'), ('Time', 'Time'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Numeric', 'Numeric'), ('BasicTimePeriod', 'BasicTimePeriod'), ('URI', 'URI')], max_length=18, null=True),
        ),
    ]
