# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20170210_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Integer', 'Integer'), ('URI', 'URI'), ('Short', 'Short'), ('Decimal', 'Decimal'), ('BigInteger', 'BigInteger'), ('Count', 'Count'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Time', 'Time'), ('Numeric', 'Numeric'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('ReportingWeek', 'ReportingWeek'), ('KeyValues', 'KeyValues'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('AlphaNumeric', 'AlphaNumeric'), ('Double', 'Double'), ('Boolean', 'Boolean'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('Float', 'Float'), ('DataSetReference', 'DataSetReference'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('GregorianDay', 'GregorianDay'), ('ReportingSemester', 'ReportingSemester'), ('TimeRange', 'TimeRange'), ('Day', 'Day'), ('InclusiveValueRange', 'InclusiveValueRange'), ('XHTML', 'XHTML'), ('Month', 'Month'), ('Long', 'Long'), ('String', 'String'), ('GregorianYear', 'GregorianYear'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingYear', 'ReportingYear'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingMonth', 'ReportingMonth'), ('MonthDay', 'MonthDay'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Alpha', 'Alpha'), ('Incremental', 'Incremental')], max_length=18, null=True),
        ),
    ]
