# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20170215_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingYear', 'ReportingYear'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Integer', 'Integer'), ('ReportingSemester', 'ReportingSemester'), ('KeyValues', 'KeyValues'), (None, 'None'), ('ReportingDay', 'ReportingDay'), ('AlphaNumeric', 'AlphaNumeric'), ('Double', 'Double'), ('Count', 'Count'), ('Incremental', 'Incremental'), ('Long', 'Long'), ('String', 'String'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingWeek', 'ReportingWeek'), ('TimeRange', 'TimeRange'), ('Time', 'Time'), ('Alpha', 'Alpha'), ('Day', 'Day'), ('IdentifiableReference', 'IdentifiableReference'), ('Month', 'Month'), ('XHTML', 'XHTML'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Boolean', 'Boolean'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Numeric', 'Numeric'), ('Decimal', 'Decimal'), ('Float', 'Float'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianDay', 'GregorianDay'), ('URI', 'URI'), ('GregorianYear', 'GregorianYear'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingMonth', 'ReportingMonth'), ('DateTime', 'DateTime'), ('MonthDay', 'MonthDay'), ('Duration', 'Duration'), ('DataSetReference', 'DataSetReference'), ('InclusiveValueRange', 'InclusiveValueRange'), ('BigInteger', 'BigInteger')], max_length=18, null=True),
        ),
    ]
