# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20170215_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='component',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='uri',
            field=models.URLField(blank=True, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='urn',
            field=models.URLField(blank=True, null=True, verbose_name='urn'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Count', 'Count'), ('Time', 'Time'), ('Long', 'Long'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Decimal', 'Decimal'), ('ReportingYear', 'ReportingYear'), ('ReportingSemester', 'ReportingSemester'), ('TimeRange', 'TimeRange'), ('Alpha', 'Alpha'), ('Integer', 'Integer'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Month', 'Month'), ('KeyValues', 'KeyValues'), ('DataSetReference', 'DataSetReference'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('Double', 'Double'), ('DateTime', 'DateTime'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYear', 'GregorianYear'), ('GregorianDay', 'GregorianDay'), ('IdentifiableReference', 'IdentifiableReference'), ('Short', 'Short'), ('MonthDay', 'MonthDay'), ('XHTML', 'XHTML'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ExclusiveValueRange', 'ExclusiveValueRange'), (None, 'None'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Numeric', 'Numeric'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingQuarter', 'ReportingQuarter'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('Boolean', 'Boolean'), ('ReportingMonth', 'ReportingMonth'), ('ReportingWeek', 'ReportingWeek'), ('String', 'String'), ('ReportingDay', 'ReportingDay'), ('Duration', 'Duration'), ('Incremental', 'Incremental'), ('ReportingTrimester', 'ReportingTrimester'), ('URI', 'URI'), ('Float', 'Float')], max_length=18, null=True),
        ),
    ]
