# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_auto_20170215_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='component',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='urn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Integer', 'Integer'), ('Count', 'Count'), ('GregorianDay', 'GregorianDay'), ('ReportingSemester', 'ReportingSemester'), ('DateTime', 'DateTime'), ('DataSetReference', 'DataSetReference'), ('InclusiveValueRange', 'InclusiveValueRange'), ('TimeRange', 'TimeRange'), ('GregorianYear', 'GregorianYear'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingQuarter', 'ReportingQuarter'), ('KeyValues', 'KeyValues'), ('Duration', 'Duration'), ('Short', 'Short'), ('Alpha', 'Alpha'), ('AlphaNumeric', 'AlphaNumeric'), ('Day', 'Day'), ('ReportingWeek', 'ReportingWeek'), ('IdentifiableReference', 'IdentifiableReference'), ('Boolean', 'Boolean'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingMonth', 'ReportingMonth'), ('BigInteger', 'BigInteger'), ('GregorianYearMonth', 'GregorianYearMonth'), ('XHTML', 'XHTML'), ('String', 'String'), ('Month', 'Month'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('Numeric', 'Numeric'), ('Decimal', 'Decimal'), ('Incremental', 'Incremental'), ('ReportingDay', 'ReportingDay'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), (None, 'None'), ('Long', 'Long'), ('Double', 'Double'), ('MonthDay', 'MonthDay'), ('Time', 'Time'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ReportingYear', 'ReportingYear'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Float', 'Float')], max_length=18, null=True),
        ),
    ]
