# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_auto_20170216_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('Double', 'Double'), ('AlphaNumeric', 'AlphaNumeric'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingWeek', 'ReportingWeek'), ('DateTime', 'DateTime'), ('Time', 'Time'), ('Float', 'Float'), ('Count', 'Count'), ('GregorianDay', 'GregorianDay'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Month', 'Month'), (None, 'None'), ('Duration', 'Duration'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Boolean', 'Boolean'), ('Day', 'Day'), ('Long', 'Long'), ('BigInteger', 'BigInteger'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ReportingQuarter', 'ReportingQuarter'), ('Alpha', 'Alpha'), ('Incremental', 'Incremental'), ('ReportingDay', 'ReportingDay'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('IdentifiableReference', 'IdentifiableReference'), ('ReportingMonth', 'ReportingMonth'), ('TimeRange', 'TimeRange'), ('DataSetReference', 'DataSetReference'), ('URI', 'URI'), ('GregorianYear', 'GregorianYear'), ('MonthDay', 'MonthDay'), ('Short', 'Short'), ('StandardTimePeriod', 'StandardTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('String', 'String'), ('ReportingYear', 'ReportingYear')], max_length=18, null=True),
        ),
    ]
