# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_auto_20170218_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('BigInteger', 'BigInteger'), ('Short', 'Short'), ('String', 'String'), ('Float', 'Float'), ('InclusiveValueRange', 'InclusiveValueRange'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('TimeRange', 'TimeRange'), ('Duration', 'Duration'), ('IdentifiableReference', 'IdentifiableReference'), ('AlphaNumeric', 'AlphaNumeric'), ('Long', 'Long'), ('ReportingSemester', 'ReportingSemester'), ('ReportingWeek', 'ReportingWeek'), ('GregorianYear', 'GregorianYear'), ('Month', 'Month'), ('Decimal', 'Decimal'), ('Boolean', 'Boolean'), ('ReportingTrimester', 'ReportingTrimester'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('Day', 'Day'), ('URI', 'URI'), ('Count', 'Count'), ('DataSetReference', 'DataSetReference'), ('Numeric', 'Numeric'), ('Alpha', 'Alpha'), ('Integer', 'Integer'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('DateTime', 'DateTime'), ('Time', 'Time'), ('MonthDay', 'MonthDay'), ('KeyValues', 'KeyValues'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Incremental', 'Incremental'), ('XHTML', 'XHTML'), ('ReportingYear', 'ReportingYear'), (None, 'None'), ('Double', 'Double')], max_length=18, null=True),
        ),
    ]
