# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_auto_20170218_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('String', 'String'), ('Integer', 'Integer'), ('Long', 'Long'), ('Decimal', 'Decimal'), ('Incremental', 'Incremental'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianDay', 'GregorianDay'), ('ReportingTrimester', 'ReportingTrimester'), ('StandardTimePeriod', 'StandardTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Count', 'Count'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingDay', 'ReportingDay'), ('XHTML', 'XHTML'), (None, 'None'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('ReportingSemester', 'ReportingSemester'), ('ReportingQuarter', 'ReportingQuarter'), ('DataSetReference', 'DataSetReference'), ('Alpha', 'Alpha'), ('ReportingYear', 'ReportingYear'), ('Day', 'Day'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('ReportingWeek', 'ReportingWeek'), ('Numeric', 'Numeric'), ('Boolean', 'Boolean'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Month', 'Month'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Double', 'Double'), ('MonthDay', 'MonthDay'), ('Short', 'Short'), ('GregorianYear', 'GregorianYear'), ('KeyValues', 'KeyValues'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ReportingMonth', 'ReportingMonth'), ('Duration', 'Duration'), ('Time', 'Time'), ('IdentifiableReference', 'IdentifiableReference'), ('URI', 'URI'), ('Float', 'Float')], max_length=18, null=True),
        ),
    ]
