# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170225_1123'),
        ('structure', '0013_auto_20170225_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='Annotations',
        ),
        migrations.RemoveField(
            model_name='componentlist',
            name='Annotations',
        ),
        migrations.AddField(
            model_name='component',
            name='annotations',
            field=models.ManyToManyField(related_name='_component_annotations_+', to='common.Annotation'),
        ),
        migrations.AddField(
            model_name='componentlist',
            name='annotations',
            field=models.ManyToManyField(related_name='_componentlist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Long', 'Long'), ('XHTML', 'XHTML'), ('AlphaNumeric', 'AlphaNumeric'), ('Short', 'Short'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('GregorianDay', 'GregorianDay'), ('DateTime', 'DateTime'), ('BigInteger', 'BigInteger'), ('Day', 'Day'), ('Alpha', 'Alpha'), ('ReportingQuarter', 'ReportingQuarter'), ('DataSetReference', 'DataSetReference'), ('StandardTimePeriod', 'StandardTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingMonth', 'ReportingMonth'), ('ReportingWeek', 'ReportingWeek'), ('Month', 'Month'), ('Double', 'Double'), ('MonthDay', 'MonthDay'), ('Time', 'Time'), ('IdentifiableReference', 'IdentifiableReference'), ('TimeRange', 'TimeRange'), ('Duration', 'Duration'), ('Integer', 'Integer'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingYear', 'ReportingYear'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('URI', 'URI'), ('ReportingTrimester', 'ReportingTrimester'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Numeric', 'Numeric'), ('GregorianYear', 'GregorianYear'), ('GregorianTimePeriod', 'GregorianTimePeriod'), (None, 'None'), ('Decimal', 'Decimal'), ('Count', 'Count'), ('ReportingDay', 'ReportingDay'), ('KeyValues', 'KeyValues'), ('String', 'String'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Incremental', 'Incremental')], max_length=18, null=True),
        ),
    ]
