# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_auto_20170225_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('Incremental', 'Incremental'), ('StandardTimePeriod', 'StandardTimePeriod'), ('DateTime', 'DateTime'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Float', 'Float'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('GregorianDay', 'GregorianDay'), ('Month', 'Month'), ('MonthDay', 'MonthDay'), ('Duration', 'Duration'), ('String', 'String'), (None, 'None'), ('Short', 'Short'), ('TimeRange', 'TimeRange'), ('Day', 'Day'), ('IdentifiableReference', 'IdentifiableReference'), ('DataSetReference', 'DataSetReference'), ('Integer', 'Integer'), ('Long', 'Long'), ('ReportingTrimester', 'ReportingTrimester'), ('BigInteger', 'BigInteger'), ('Double', 'Double'), ('AlphaNumeric', 'AlphaNumeric'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('Alpha', 'Alpha'), ('Decimal', 'Decimal'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingWeek', 'ReportingWeek'), ('Time', 'Time'), ('ReportingYear', 'ReportingYear'), ('ReportingMonth', 'ReportingMonth'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('Boolean', 'Boolean'), ('ReportingDay', 'ReportingDay')], max_length=18, null=True),
        ),
    ]
