# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_auto_20170228_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('dimension', 'dimenstion'), ('measureDimension', 'measureDimension')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='component',
            name='objectType',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Any', 'Any'), ('Agency', 'Agency'), ('AgencyScheme', 'AgencyScheme'), ('AttachmentConstraint', 'AttachmentConstraint'), ('Attribute', 'Attribute'), ('AttributeDescriptor', 'AttributeDescriptor'), ('Categorisation', 'Categorisation'), ('Category', 'Category'), ('CategorySchemeMap', 'CategorySchemeMap'), ('CategoryScheme', 'CategoryScheme'), ('Code', 'Code'), ('CodeMap', 'CodeMap'), ('Codelist', 'Codelist'), ('CodelistMap', 'CodelistMap'), ('ComponentMap', 'ComponentMap'), ('Concept', 'Concept'), ('ConceptMap', 'ConceptMap'), ('ConceptScheme', 'ConceptScheme'), ('ConceptSchemeMap', 'ConceptSchemeMap'), ('Constraint', 'Constraint'), ('ConstraintTarget', 'ConstraintTarget'), ('ContentConstraint', 'ContentConstraint'), ('Dataflow', 'Dataflow'), ('DataConsumer', 'DataConsumer'), ('DataConsumerScheme', 'DataConsumerScheme'), ('DataProvider', 'DataProvider'), ('DataProviderScheme', 'DataProviderScheme'), ('DataSetTarget', 'DataSetTarget'), ('DataStructure', 'DataStructure'), ('Dimension', 'Dimension'), ('DimensionDescriptor', 'DimensionDescriptor'), ('DimensionDescriptorValuesTarget', 'DimensionDescriptorValuesTarget'), ('GroupDimensionDescriptor', 'GroupDimensionDescriptor'), ('HierarchicalCode', 'HierarchicalCode'), ('HierarchicalCodelist', 'HierarchicalCodelist'), ('Hierarchy', 'Hierarchy'), ('HybridCodelistMap', 'HybridCodelistMap'), ('HybridCodeMap', 'HybridCodeMap'), ('IdentifiableObjectTarget', 'IdentifiableObjectTarget'), ('Level', 'Level'), ('MeasureDescriptor', 'MeasureDescriptor'), ('MeasureDimension', 'MeasureDimension'), ('Metadataflow', 'Metadataflow'), ('MetadataAttribute', 'MetadataAttribute'), ('MetadataSet', 'MetadataSet'), ('MetadataStructure', 'MetadataStructure'), ('MetadataTarget', 'MetadataTarget'), ('Organisation', 'Organisation'), ('OrganisationMap', 'OrganisationMap'), ('OrganisationScheme', 'OrganisationScheme'), ('OrganisationSchemeMap', 'OrganisationSchemeMap'), ('OrganisationUnit', 'OrganisationUnit'), ('OrganisationUnitScheme', 'OrganisationUnitScheme'), ('PrimaryMeasure', 'PrimaryMeasure'), ('Process', 'Process'), ('ProcessStep', 'ProcessStep'), ('ProvisionAgreement', 'ProvisionAgreement'), ('ReportingCategory', 'ReportingCategory'), ('ReportingCategoryMap', 'ReportingCategoryMap'), ('ReportingTaxonomy', 'ReportingTaxonomy'), ('ReportingTaxonomyMap', 'ReportingTaxonomyMap'), ('ReportingYearStartDay', 'ReportingYearStartDay'), ('ReportPeriodTarget', 'ReportPeriodTarget'), ('ReportStructure', 'ReportStructure'), ('StructureMap', 'StructureMap'), ('StructureSet', 'StructureSet'), ('TimeDimension', 'TimeDimension'), ('Transition', 'Transition')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z0-9_@$\\-]+', 32), 'Enter a value of type IDType that has pattern "([A-Za-z0-9_@$\\-]+)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('ReportingTimePeriod', 'ReportingTimePeriod'), ('Double', 'Double'), ('ReportingDay', 'ReportingDay'), ('String', 'String'), ('Long', 'Long'), ('Short', 'Short'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianYear', 'GregorianYear'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingMonth', 'ReportingMonth'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('XHTML', 'XHTML'), ('DataSetReference', 'DataSetReference'), ('Decimal', 'Decimal'), ('Alpha', 'Alpha'), ('Float', 'Float'), ('ReportingWeek', 'ReportingWeek'), ('Month', 'Month'), ('IdentifiableReference', 'IdentifiableReference'), ('MonthDay', 'MonthDay'), ('Integer', 'Integer'), ('Numeric', 'Numeric'), ('KeyValues', 'KeyValues'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Count', 'Count'), ('BigInteger', 'BigInteger'), ('AlphaNumeric', 'AlphaNumeric'), (None, 'None'), ('Day', 'Day'), ('Boolean', 'Boolean'), ('Incremental', 'Incremental'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianDay', 'GregorianDay'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Time', 'Time'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ReportingYear', 'ReportingYear'), ('ReportingSemester', 'ReportingSemester'), ('InclusiveValueRange', 'InclusiveValueRange')], max_length=255, null=True),
        ),
    ]
