# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_auto_20170228_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Long', 'Long'), ('Decimal', 'Decimal'), ('String', 'String'), ('Float', 'Float'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('KeyValues', 'KeyValues'), ('Month', 'Month'), ('Alpha', 'Alpha'), ('ReportingYear', 'ReportingYear'), ('IdentifiableReference', 'IdentifiableReference'), ('Count', 'Count'), ('ReportingSemester', 'ReportingSemester'), ('DateTime', 'DateTime'), ('Time', 'Time'), (None, 'None'), ('GregorianYear', 'GregorianYear'), ('Day', 'Day'), ('XHTML', 'XHTML'), ('BigInteger', 'BigInteger'), ('AlphaNumeric', 'AlphaNumeric'), ('Short', 'Short'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('MonthDay', 'MonthDay'), ('Incremental', 'Incremental'), ('Numeric', 'Numeric'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Boolean', 'Boolean'), ('URI', 'URI'), ('ReportingDay', 'ReportingDay'), ('ReportingWeek', 'ReportingWeek'), ('Double', 'Double'), ('TimeRange', 'TimeRange'), ('DataSetReference', 'DataSetReference'), ('Integer', 'Integer'), ('Duration', 'Duration'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('InclusiveValueRange', 'InclusiveValueRange')], max_length=255, null=True),
        ),
    ]
