# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_auto_20170228_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('URI', 'URI'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Numeric', 'Numeric'), ('Decimal', 'Decimal'), ('Float', 'Float'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYear', 'GregorianYear'), ('XHTML', 'XHTML'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), (None, 'None'), ('AlphaNumeric', 'AlphaNumeric'), ('Count', 'Count'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingWeek', 'ReportingWeek'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Alpha', 'Alpha'), ('Long', 'Long'), ('Boolean', 'Boolean'), ('ReportingMonth', 'ReportingMonth'), ('Incremental', 'Incremental'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Day', 'Day'), ('Time', 'Time'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingYear', 'ReportingYear'), ('DataSetReference', 'DataSetReference'), ('ReportingDay', 'ReportingDay'), ('BigInteger', 'BigInteger'), ('Short', 'Short'), ('Double', 'Double'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ReportingQuarter', 'ReportingQuarter'), ('MonthDay', 'MonthDay'), ('Month', 'Month'), ('KeyValues', 'KeyValues'), ('Integer', 'Integer'), ('GregorianDay', 'GregorianDay'), ('Duration', 'Duration'), ('IdentifiableReference', 'IdentifiableReference'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('String', 'String'), ('TimeRange', 'TimeRange'), ('DateTime', 'DateTime')], max_length=255, null=True),
        ),
    ]
