# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_auto_20170228_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_component_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='annotations',
            field=models.ManyToManyField(null=True, related_name='_componentlist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('String', 'String'), (None, 'None'), ('Integer', 'Integer'), ('Float', 'Float'), ('ReportingWeek', 'ReportingWeek'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), ('Double', 'Double'), ('ReportingMonth', 'ReportingMonth'), ('MonthDay', 'MonthDay'), ('IdentifiableReference', 'IdentifiableReference'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('DataSetReference', 'DataSetReference'), ('URI', 'URI'), ('Day', 'Day'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('AlphaNumeric', 'AlphaNumeric'), ('TimeRange', 'TimeRange'), ('Month', 'Month'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Alpha', 'Alpha'), ('GregorianDay', 'GregorianDay'), ('KeyValues', 'KeyValues'), ('ReportingYear', 'ReportingYear'), ('Time', 'Time'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('Incremental', 'Incremental'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingSemester', 'ReportingSemester'), ('GregorianYear', 'GregorianYear'), ('ReportingQuarter', 'ReportingQuarter'), ('Decimal', 'Decimal'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Long', 'Long'), ('Short', 'Short'), ('Boolean', 'Boolean'), ('Count', 'Count'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('BigInteger', 'BigInteger')], max_length=255, null=True),
        ),
    ]
