# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0020_auto_20170228_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('AlphaNumeric', 'AlphaNumeric'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('Month', 'Month'), ('KeyValues', 'KeyValues'), ('IdentifiableReference', 'IdentifiableReference'), ('Boolean', 'Boolean'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), (None, 'None'), ('BigInteger', 'BigInteger'), ('DateTime', 'DateTime'), ('Time', 'Time'), ('DataSetReference', 'DataSetReference'), ('MonthDay', 'MonthDay'), ('ReportingQuarter', 'ReportingQuarter'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Count', 'Count'), ('ReportingYear', 'ReportingYear'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('XHTML', 'XHTML'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingWeek', 'ReportingWeek'), ('URI', 'URI'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Decimal', 'Decimal'), ('Alpha', 'Alpha'), ('Short', 'Short'), ('String', 'String'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Incremental', 'Incremental'), ('ReportingSemester', 'ReportingSemester'), ('ReportingDay', 'ReportingDay'), ('TimeRange', 'TimeRange'), ('Long', 'Long'), ('Float', 'Float'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYear', 'GregorianYear'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Duration', 'Duration'), ('ReportingTrimester', 'ReportingTrimester'), ('Double', 'Double')], max_length=255, null=True),
        ),
    ]
