# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0021_auto_20170228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id_code',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id_code',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Integer', 'Integer'), ('Double', 'Double'), ('BigInteger', 'BigInteger'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingYear', 'ReportingYear'), ('Float', 'Float'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianYear', 'GregorianYear'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingDay', 'ReportingDay'), ('Month', 'Month'), ('MonthDay', 'MonthDay'), ('Alpha', 'Alpha'), ('ReportingMonth', 'ReportingMonth'), ('URI', 'URI'), ('Count', 'Count'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingSemester', 'ReportingSemester'), ('Long', 'Long'), ('TimeRange', 'TimeRange'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('Numeric', 'Numeric'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Boolean', 'Boolean'), ('AlphaNumeric', 'AlphaNumeric'), ('Day', 'Day'), ('DataSetReference', 'DataSetReference'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('GregorianDay', 'GregorianDay'), ('Time', 'Time'), ('String', 'String'), ('Decimal', 'Decimal'), ('Incremental', 'Incremental'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingWeek', 'ReportingWeek'), ('IdentifiableReference', 'IdentifiableReference'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('DateTime', 'DateTime'), (None, 'None'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Short', 'Short'), ('Duration', 'Duration')], max_length=255, null=True),
        ),
    ]
