# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0022_auto_20170228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('ReportingDay', 'ReportingDay'), ('BigInteger', 'BigInteger'), ('Decimal', 'Decimal'), ('GregorianDay', 'GregorianDay'), ('ReportingYear', 'ReportingYear'), ('ReportingTrimester', 'ReportingTrimester'), ('MonthDay', 'MonthDay'), ('Incremental', 'Incremental'), ('Day', 'Day'), ('DataSetReference', 'DataSetReference'), ('Numeric', 'Numeric'), ('String', 'String'), ('DateTime', 'DateTime'), ('Month', 'Month'), ('TimeRange', 'TimeRange'), ('Count', 'Count'), ('ReportingSemester', 'ReportingSemester'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('InclusiveValueRange', 'InclusiveValueRange'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Time', 'Time'), (None, 'None'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), ('ReportingMonth', 'ReportingMonth'), ('IdentifiableReference', 'IdentifiableReference'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Double', 'Double'), ('ReportingWeek', 'ReportingWeek'), ('AlphaNumeric', 'AlphaNumeric'), ('Long', 'Long'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('Alpha', 'Alpha'), ('Integer', 'Integer'), ('Float', 'Float'), ('URI', 'URI'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianYear', 'GregorianYear'), ('KeyValues', 'KeyValues'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Boolean', 'Boolean'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Short', 'Short')], max_length=255, null=True),
        ),
    ]
