# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_auto_20170228_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('StandardTimePeriod', 'StandardTimePeriod'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Incremental', 'Incremental'), ('Boolean', 'Boolean'), ('ReportingMonth', 'ReportingMonth'), ('Alpha', 'Alpha'), ('Short', 'Short'), ('GregorianDay', 'GregorianDay'), ('BigInteger', 'BigInteger'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Month', 'Month'), ('DataSetReference', 'DataSetReference'), (None, 'None'), ('ReportingQuarter', 'ReportingQuarter'), ('MonthDay', 'MonthDay'), ('DateTime', 'DateTime'), ('AlphaNumeric', 'AlphaNumeric'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('ReportingDay', 'ReportingDay'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Numeric', 'Numeric'), ('ReportingWeek', 'ReportingWeek'), ('GregorianYear', 'GregorianYear'), ('Integer', 'Integer'), ('URI', 'URI'), ('Count', 'Count'), ('Long', 'Long'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('String', 'String'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingYear', 'ReportingYear'), ('TimeRange', 'TimeRange'), ('Day', 'Day'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Float', 'Float')], max_length=255, null=True),
        ),
    ]
