# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_auto_20170301_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_component_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_componentlist_annotations_+', to='common.Annotation'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('GregorianYearMonth', 'GregorianYearMonth'), ('MonthDay', 'MonthDay'), ('Alpha', 'Alpha'), ('Integer', 'Integer'), ('Float', 'Float'), ('InclusiveValueRange', 'InclusiveValueRange'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('Long', 'Long'), ('Short', 'Short'), ('AlphaNumeric', 'AlphaNumeric'), ('Boolean', 'Boolean'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingWeek', 'ReportingWeek'), ('URI', 'URI'), ('XHTML', 'XHTML'), ('Incremental', 'Incremental'), ('TimeRange', 'TimeRange'), ('Decimal', 'Decimal'), ('BasicTimePeriod', 'BasicTimePeriod'), ('BigInteger', 'BigInteger'), ('Double', 'Double'), ('DateTime', 'DateTime'), ('KeyValues', 'KeyValues'), ('Day', 'Day'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Month', 'Month'), ('Numeric', 'Numeric'), ('DataSetReference', 'DataSetReference'), ('Time', 'Time'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianYear', 'GregorianYear'), ('Count', 'Count'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('Duration', 'Duration'), ('IdentifiableReference', 'IdentifiableReference'), ('String', 'String'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingYear', 'ReportingYear'), ('ReportingDay', 'ReportingDay'), ('GregorianTimePeriod', 'GregorianTimePeriod'), (None, 'None')], max_length=255, null=True),
        ),
    ]
