# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0025_auto_20170302_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Double', 'Double'), ('Float', 'Float'), ('URI', 'URI'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Count', 'Count'), ('MonthDay', 'MonthDay'), ('Numeric', 'Numeric'), ('ReportingWeek', 'ReportingWeek'), ('Time', 'Time'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('DataSetReference', 'DataSetReference'), ('AlphaNumeric', 'AlphaNumeric'), ('Decimal', 'Decimal'), ('GregorianDay', 'GregorianDay'), ('IdentifiableReference', 'IdentifiableReference'), ('ReportingDay', 'ReportingDay'), (None, 'None'), ('String', 'String'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('InclusiveValueRange', 'InclusiveValueRange'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Integer', 'Integer'), ('GregorianYearMonth', 'GregorianYearMonth'), ('KeyValues', 'KeyValues'), ('Alpha', 'Alpha'), ('Incremental', 'Incremental'), ('GregorianYear', 'GregorianYear'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('XHTML', 'XHTML'), ('BigInteger', 'BigInteger'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Long', 'Long'), ('DateTime', 'DateTime'), ('Month', 'Month'), ('ReportingYear', 'ReportingYear'), ('ReportingQuarter', 'ReportingQuarter'), ('Day', 'Day'), ('Duration', 'Duration'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingMonth', 'ReportingMonth'), ('TimeRange', 'TimeRange'), ('Boolean', 'Boolean')], max_length=255, null=True),
        ),
    ]
