# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_auto_20170310_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('BigInteger', 'BigInteger'), ('Count', 'Count'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Day', 'Day'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), ('DataSetReference', 'DataSetReference'), ('Decimal', 'Decimal'), ('MonthDay', 'MonthDay'), ('Time', 'Time'), ('BasicTimePeriod', 'BasicTimePeriod'), ('TimeRange', 'TimeRange'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Double', 'Double'), ('Long', 'Long'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('AlphaNumeric', 'AlphaNumeric'), ('Short', 'Short'), ('Incremental', 'Incremental'), ('GregorianYear', 'GregorianYear'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingWeek', 'ReportingWeek'), ('Numeric', 'Numeric'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('URI', 'URI'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingDay', 'ReportingDay'), ('Month', 'Month'), ('KeyValues', 'KeyValues'), ('Alpha', 'Alpha'), ('Float', 'Float'), ('ReportingMonth', 'ReportingMonth'), ('Integer', 'Integer'), ('GregorianYearMonth', 'GregorianYearMonth'), (None, 'None'), ('Boolean', 'Boolean'), ('ReportingYear', 'ReportingYear'), ('DateTime', 'DateTime'), ('String', 'String')], max_length=255, null=True),
        ),
    ]
