# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_auto_20170313_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('GregorianTimePeriod', 'GregorianTimePeriod'), ('KeyValues', 'KeyValues'), ('AlphaNumeric', 'AlphaNumeric'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingMonth', 'ReportingMonth'), ('ReportingWeek', 'ReportingWeek'), ('ReportingDay', 'ReportingDay'), ('Duration', 'Duration'), ('Incremental', 'Incremental'), ('DataSetReference', 'DataSetReference'), ('Long', 'Long'), ('ReportingSemester', 'ReportingSemester'), ('Integer', 'Integer'), ('Day', 'Day'), ('DateTime', 'DateTime'), ('Float', 'Float'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYear', 'GregorianYear'), ('Numeric', 'Numeric'), ('TimeRange', 'TimeRange'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('Time', 'Time'), ('InclusiveValueRange', 'InclusiveValueRange'), ('MonthDay', 'MonthDay'), (None, 'None'), ('URI', 'URI'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('String', 'String'), ('GregorianDay', 'GregorianDay'), ('IdentifiableReference', 'IdentifiableReference'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Alpha', 'Alpha'), ('BigInteger', 'BigInteger'), ('XHTML', 'XHTML'), ('Boolean', 'Boolean'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Short', 'Short'), ('Decimal', 'Decimal')], max_length=255, null=True),
        ),
    ]
