# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0028_auto_20170313_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='textType',
            field=models.CharField(blank=True, choices=[('ExclusiveValueRange', 'ExclusiveValueRange'), ('BigInteger', 'BigInteger'), ('Decimal', 'Decimal'), ('ReportingSemester', 'ReportingSemester'), ('MonthDay', 'MonthDay'), ('Time', 'Time'), ('AlphaNumeric', 'AlphaNumeric'), ('Long', 'Long'), ('Day', 'Day'), ('XHTML', 'XHTML'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianYear', 'GregorianYear'), ('IdentifiableReference', 'IdentifiableReference'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Month', 'Month'), ('Double', 'Double'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingYear', 'ReportingYear'), ('Duration', 'Duration'), ('URI', 'URI'), (None, 'None'), ('KeyValues', 'KeyValues'), ('Float', 'Float'), ('ReportingTrimester', 'ReportingTrimester'), ('DataSetReference', 'DataSetReference'), ('String', 'String'), ('ReportingMonth', 'ReportingMonth'), ('ReportingWeek', 'ReportingWeek'), ('ReportingQuarter', 'ReportingQuarter'), ('Alpha', 'Alpha'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Count', 'Count'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Incremental', 'Incremental'), ('GregorianDay', 'GregorianDay'), ('ReportingDay', 'ReportingDay'), ('Boolean', 'Boolean'), ('Short', 'Short')], max_length=255, null=True),
        ),
    ]
