# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalname',
            old_name='lang',
            new_name='language',
        ),
    ]
