# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeValueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Code')),
            ],
        ),
        migrations.CreateModel(
            name='ContentConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('periodicity', models.CharField(blank=True, max_length=63)),
                ('offset', models.CharField(blank=True, max_length=63)),
                ('tolerance', models.CharField(blank=True, max_length=63)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('data_structures', models.ManyToManyField(blank=True, related_name='content_constraints', to='hydro_sdmx.DataStructure')),
                ('dataflows', models.ManyToManyField(blank=True, related_name='dataflow_content_constraints', to='hydro_sdmx.Dataflow')),
                ('dataproviders', models.ManyToManyField(blank=True, related_name='content_constraints', to='hydro_sdmx.Organisation')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_content_constraints', to='hydro_sdmx.Dataflow')),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_constraints', to='hydro_sdmx.Source')),
                ('provisions', models.ManyToManyField(blank=True, related_name='content_constraints', to='hydro_sdmx.DataProvisionAgreement')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.Registration')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CubeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True)),
                ('content_constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cube_regions', to='hydro_sdmx.ContentConstraint')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(blank=True, max_length=255)),
                ('attribute', models.CharField(blank=True, max_length=255)),
                ('string_values', models.CharField(blank=True, max_length=511)),
                ('start_time', models.CharField(blank=True, max_length=63, null=True)),
                ('end_time', models.CharField(blank=True, max_length=63, null=True)),
                ('start_inclusive', models.NullBooleanField()),
                ('end_inclusive', models.NullBooleanField()),
                ('code_values', models.ManyToManyField(through='hydro_sdmx.CodeValueDetail', to='hydro_sdmx.Code')),
                ('cube_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_value_sets', to='hydro_sdmx.CubeRegion')),
            ],
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='data_structures',
            field=models.ManyToManyField(blank=True, related_name='attachemt_constraints', to='hydro_sdmx.DataStructure'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='dataflows',
            field=models.ManyToManyField(blank=True, related_name='dataflow_attachment_constraints', to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='datasets',
            field=models.ManyToManyField(related_name='dataset_attachment_constraints', to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='datasources',
            field=models.ManyToManyField(blank=True, related_name='attachment_constraints', to='hydro_sdmx.Source'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='provisions',
            field=models.ManyToManyField(blank=True, related_name='attachment_constraints', to='hydro_sdmx.DataProvisionAgreement'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Float', 'Float'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('Incremental', 'Incremental'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Long', 'Long'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('MonthDay', 'MonthDay'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('String', 'String'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('ReportingMonth', 'ReportingMonth'), ('KeyValues', 'KeyValues'), ('ReportingWeek', 'ReportingWeek'), ('Boolean', 'Boolean'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('DataSetReference', 'DataSetReference'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod')], max_length=63),
        ),
        migrations.AlterField(
            model_name='concept',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Float', 'Float'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('Incremental', 'Incremental'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Long', 'Long'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('MonthDay', 'MonthDay'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('String', 'String'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('ReportingMonth', 'ReportingMonth'), ('KeyValues', 'KeyValues'), ('ReportingWeek', 'ReportingWeek'), ('Boolean', 'Boolean'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('DataSetReference', 'DataSetReference'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod')], max_length=63),
        ),
        migrations.AlterField(
            model_name='datakeyset',
            name='attachment_constraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_key_sets', to='hydro_sdmx.AttachmentConstraint'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Float', 'Float'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('Incremental', 'Incremental'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Long', 'Long'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('MonthDay', 'MonthDay'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('String', 'String'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('ReportingMonth', 'ReportingMonth'), ('KeyValues', 'KeyValues'), ('ReportingWeek', 'ReportingWeek'), ('Boolean', 'Boolean'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('DataSetReference', 'DataSetReference'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod')], max_length=63),
        ),
        migrations.AlterField(
            model_name='measure',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Float', 'Float'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('BigInteger', 'BigInteger'), ('Incremental', 'Incremental'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('ReportingDay', 'ReportingDay'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Numeric', 'Numeric'), ('Integer', 'Integer'), ('Double', 'Double'), ('Count', 'Count'), ('GregorianYear', 'GregorianYear'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Day', 'Day'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Long', 'Long'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('MonthDay', 'MonthDay'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('String', 'String'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('ReportingMonth', 'ReportingMonth'), ('KeyValues', 'KeyValues'), ('ReportingWeek', 'ReportingWeek'), ('Boolean', 'Boolean'), ('ReportingQuarter', 'ReportingQuarter'), ('Duration', 'Duration'), ('DataSetReference', 'DataSetReference'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('BasicTimePeriod', 'BasicTimePeriod')], max_length=63),
        ),
        migrations.AddField(
            model_name='codevaluedetail',
            name='key_value_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_value_details', to='hydro_sdmx.KeyValueSet'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='contentconstraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.ContentConstraint'),
        ),
        migrations.AddField(
            model_name='datakeyset',
            name='content_constraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_key_sets', to='hydro_sdmx.ContentConstraint'),
        ),
        migrations.AlterUniqueTogether(
            name='keyvalueset',
            unique_together=set([('cube_region', 'dimension', 'attribute')]),
        ),
        migrations.AddIndex(
            model_name='contentconstraint',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_6d6182_idx'),
        ),
        migrations.AddIndex(
            model_name='contentconstraint',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_2061fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contentconstraint',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__ef1161_idx'),
        ),
        migrations.AddIndex(
            model_name='contentconstraint',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_b631f3_idx'),
        ),
        migrations.AddIndex(
            model_name='contentconstraint',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_022e60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentconstraint',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
    ]
