# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0002_auto_20170921_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id_code',
            field=models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z][A-Za-z0-9_\\-]*', 32), 'Enter a value of type NCNameIDType that has pattern "([A-Za-z][A-Za-z0-9_\\-]*)"', 'invalid_pattern')], verbose_name='ID'),
        ),
    ]
