# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0002_auto_20171027_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationaldescription',
            old_name='description',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='internationalname',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='internationalname',
            name='contact_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hydro_sdmx.Contact'),
        ),
    ]
