# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0003_auto_20170921_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='wrapper',
            new_name='organisation',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_text',
            field=models.TextField(blank=True, verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_title',
            field=models.CharField(blank=True, max_length=127, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(blank=True, max_length=63, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id_code',
            field=models.CharField(blank=True, max_length=63, verbose_name='ID'),
        ),
    ]
