# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0003_auto_20171027_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternationalDescription',
            new_name='Description',
        ),
        migrations.RenameModel(
            old_name='InternationalName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='value',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='value',
            new_name='text',
        ),
    ]
