# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0004_auto_20171104_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataProvisionAgreement',
            new_name='ProvisionAgreement',
        ),
        migrations.RemoveIndex(
            model_name='provisionagreement',
            name='hydro_sdmx__id_code_60c01d_idx',
        ),
        migrations.RemoveIndex(
            model_name='provisionagreement',
            name='hydro_sdmx__agency__a1a9bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='provisionagreement',
            name='hydro_sdmx__id_code_5c8bcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='provisionagreement',
            name='hydro_sdmx__id_code_8375a4_idx',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='dataprovisionagreement',
            new_name='provisionagreement',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='dataprovisionagreement',
            new_name='provisionagreement',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='dataprovisionagreement',
            new_name='provisionagreement',
        ),
        migrations.RemoveField(
            model_name='contentconstraint',
            name='dataproviders',
        ),
        migrations.AddField(
            model_name='contentconstraint',
            name='data_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_constraints', to='hydro_sdmx.Organisation'),
        ),
        migrations.AlterField(
            model_name='code',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Codelist', verbose_name='Codelist'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.ConceptScheme', verbose_name='Concept Scheme'),
        ),
        migrations.AddIndex(
            model_name='provisionagreement',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_e2c538_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionagreement',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__9734c9_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionagreement',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_2c5a19_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionagreement',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_81e9cb_idx'),
        ),
    ]
