# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0004_auto_20170922_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_organisation_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='value',
            field=models.CharField(max_length=31, verbose_name='number'),
        ),
    ]
