# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0005_auto_20171113_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='is_multiLingual',
            new_name='is_multi_lingual',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='is_multiLingual',
            new_name='is_multi_lingual',
        ),
        migrations.RenameField(
            model_name='datastructure',
            old_name='is_multiLingual',
            new_name='is_multi_lingual',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='is_multiLingual',
            new_name='is_multi_lingual',
        ),
    ]
