# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hydro_sdmx.models.registration


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0006_auto_20170922_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Append', 'Append'), ('Replace', 'Replace'), ('Delete', 'Delete')], max_length=63)),
                ('interactive', models.BooleanField(default=False)),
                ('set_id', models.CharField(max_length=63, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Contact', verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metadataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Append', 'Append'), ('Replace', 'Replace'), ('Delete', 'Delete')], max_length=63)),
                ('interactive', models.BooleanField(default=False)),
                ('set_id', models.CharField(max_length=63, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Contact', verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Append', 'Append'), ('Replace', 'Replace'), ('Delete', 'Delete')], max_length=63)),
                ('interactive', models.BooleanField(default=False)),
                ('set_id', models.CharField(max_length=63, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Contact', verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_file', models.FileField(blank=True, null=True, unique=True, upload_to=hydro_sdmx.models.registration.sdmx_upload_path)),
                ('from_url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'email addresses'},
        ),
        migrations.AlterModelOptions(
            name='fax',
            options={'verbose_name_plural': 'Faxes'},
        ),
        migrations.AlterField(
            model_name='email',
            name='value',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='fax',
            name='value',
            field=models.CharField(max_length=31, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='value',
            field=models.CharField(max_length=31, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='value',
            field=models.URLField(verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='x400',
            name='value',
            field=models.CharField(max_length=63, verbose_name='X400'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='fax',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='metastructure',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Source'),
        ),
        migrations.AddField(
            model_name='metadataset',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Source'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Source'),
        ),
    ]
