# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0006_auto_20171115_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuberegion',
            old_name='include',
            new_name='is_included',
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='data_structures',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.DataStructure'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='dataflows',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='dataset_attachmentconstraint_set', to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='datasources',
            field=models.ManyToManyField(blank=True, related_name='datasource_attachmentconstraint_set', to='hydro_sdmx.Registration'),
        ),
        migrations.AlterField(
            model_name='attachmentconstraint',
            name='provisions',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.ProvisionAgreement'),
        ),
        migrations.AlterField(
            model_name='contentconstraint',
            name='data_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_contentconstraint_set', to='hydro_sdmx.Organisation'),
        ),
        migrations.AlterField(
            model_name='contentconstraint',
            name='data_structures',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.DataStructure'),
        ),
        migrations.AlterField(
            model_name='contentconstraint',
            name='dataflows',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='contentconstraint',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_contentconstraint_set', to='hydro_sdmx.Dataflow'),
        ),
        migrations.AlterField(
            model_name='contentconstraint',
            name='provisions',
            field=models.ManyToManyField(blank=True, to='hydro_sdmx.ProvisionAgreement'),
        ),
    ]
