# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0007_auto_20170922_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_agencyscheme_annotations_+', to='hydro_sdmx.Annotation')),
                ('organisations', models.ManyToManyField(related_name='agency_schemes', to='hydro_sdmx.Organisation', verbose_name='agencies')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataConsumerScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_dataconsumerscheme_annotations_+', to='hydro_sdmx.Annotation')),
                ('organisations', models.ManyToManyField(related_name='data_consumer_schemes', to='hydro_sdmx.Organisation', verbose_name='data consumers')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataProviderScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_dataproviderscheme_annotations_+', to='hydro_sdmx.Annotation')),
                ('organisations', models.ManyToManyField(related_name='data_provider_schemes', to='hydro_sdmx.Organisation', verbose_name='data providers')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationUnitScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_organisationunitscheme_annotations_+', to='hydro_sdmx.Annotation')),
                ('organisations', models.ManyToManyField(related_name='organisation_unit_schemes', to='hydro_sdmx.Organisation', verbose_name='Organisation units')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='organisationunitscheme',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_175155_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationunitscheme',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_968062_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationunitscheme',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__7578d5_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationunitscheme',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_0b8d97_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationunitscheme',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_a72694_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationunitscheme',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='dataproviderscheme',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_4a896f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataproviderscheme',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_e19124_idx'),
        ),
        migrations.AddIndex(
            model_name='dataproviderscheme',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__e9903c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataproviderscheme',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_a9d9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='dataproviderscheme',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_293c79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataproviderscheme',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='dataconsumerscheme',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_f4158b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsumerscheme',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_05fe32_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsumerscheme',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__207861_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsumerscheme',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_15b61e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconsumerscheme',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_7a8220_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataconsumerscheme',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='agencyscheme',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_9ebf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyscheme',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_9db74b_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyscheme',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__15831d_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyscheme',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_88affd_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyscheme',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_6a4bfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyscheme',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
    ]
