# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0009_auto_20170924_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Dataset'),
        ),
        migrations.AddField(
            model_name='metadataset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Metadataset'),
        ),
        migrations.AddField(
            model_name='metastructure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.MetaStructure'),
        ),
    ]
