# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0010_auto_20170924_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Codelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z][A-Za-z0-9_\\-]*', 32), 'Enter a value of type NCNameIDType that has pattern "([A-Za-z][A-Za-z0-9_\\-]*)"', 'invalid_pattern')], verbose_name='id')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextFormatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text_type', models.CharField(blank=True, choices=[('Integer', 'Integer'), ('Long', 'Long'), ('String', 'String'), ('Boolean', 'Boolean'), ('BigInteger', 'BigInteger'), ('Count', 'Count'), ('Incremental', 'Incremental'), ('TimeRange', 'TimeRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Month', 'Month'), ('Double', 'Double'), ('ReportingWeek', 'ReportingWeek'), ('Day', 'Day'), ('KeyValues', 'KeyValues'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('MonthDay', 'MonthDay'), ('ReportingMonth', 'ReportingMonth'), ('AlphaNumeric', 'AlphaNumeric'), ('Duration', 'Duration'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('InclusiveValueRange', 'InclusiveValueRange'), ('URI', 'URI'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('Decimal', 'Decimal'), ('GregorianDay', 'GregorianDay'), ('Numeric', 'Numeric'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('Float', 'Float'), ('ReportingYear', 'ReportingYear'), ('XHTML', 'XHTML'), (None, 'None'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('DateTime', 'DateTime'), ('DataSetReference', 'DataSetReference'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingDay', 'ReportingDay'), ('Time', 'Time'), ('ReportingQuarter', 'ReportingQuarter'), ('GregorianYear', 'GregorianYear'), ('Short', 'Short')], max_length=63)),
                ('is_sequence', models.NullBooleanField()),
                ('interval', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('start_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('end_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('time_interval', models.DurationField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('decimals', models.PositiveIntegerField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('is_multiLingual', models.NullBooleanField()),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_743458_idx'),
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_f3cf38_idx'),
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['id_code', 'name'], name='hydro_sdmx__id_code_9ab18d_idx'),
        ),
        migrations.AddField(
            model_name='representation',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_representation_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='representation',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Codelist'),
        ),
        migrations.AddField(
            model_name='representation',
            name='enumeration_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='representation',
            name='text_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='codelist',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation'),
        ),
        migrations.AddField(
            model_name='codelist',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_codelist_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='codelist',
            name='codes',
            field=models.ManyToManyField(related_name='codelists', to='hydro_sdmx.Code'),
        ),
        migrations.AddField(
            model_name='codelist',
            name='registrations',
            field=models.ManyToManyField(to='hydro_sdmx.MetaStructure'),
        ),
        migrations.AddField(
            model_name='code',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_code_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='code',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Code'),
        ),
        migrations.AddIndex(
            model_name='representation',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_f5b5af_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_35528a_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_362da1_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__116c07_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_77b07a_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_6c5067_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codelist',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_0544fb_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_9183d8_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['id_code', 'name'], name='hydro_sdmx__id_code_655199_idx'),
        ),
    ]
