# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0012_auto_20170924_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='enumeration',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='enumeration_format',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='text_format',
        ),
        migrations.DeleteModel(
            name='TextFormatInfo',
        ),
        migrations.DeleteModel(
            name='Representation',
        ),
    ]
