# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0013_auto_20170924_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyscheme',
            old_name='organisations',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='dataconsumerscheme',
            old_name='organisations',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='dataproviderscheme',
            old_name='organisations',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='organisationunitscheme',
            old_name='organisations',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='codelist',
            name='codes',
        ),
        migrations.AddField(
            model_name='codelist',
            name='items',
            field=models.ManyToManyField(related_name='codelists', to='hydro_sdmx.Code', verbose_name='codes'),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='id_code',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID'),
        ),
    ]
