# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0014_auto_20170925_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextFormatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text_type', models.CharField(blank=True, choices=[('Incremental', 'Incremental'), ('Integer', 'Integer'), ('GregorianYear', 'GregorianYear'), ('String', 'String'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingQuarter', 'ReportingQuarter'), ('TimeRange', 'TimeRange'), ('GregorianYearMonth', 'GregorianYearMonth'), ('DateTime', 'DateTime'), ('AlphaNumeric', 'AlphaNumeric'), ('GregorianDay', 'GregorianDay'), ('Time', 'Time'), ('Float', 'Float'), ('URI', 'URI'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingYear', 'ReportingYear'), ('ReportingDay', 'ReportingDay'), ('Alpha', 'Alpha'), ('MonthDay', 'MonthDay'), (None, 'None'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Decimal', 'Decimal'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('Boolean', 'Boolean'), ('ReportingWeek', 'ReportingWeek'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('XHTML', 'XHTML'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Double', 'Double'), ('Long', 'Long'), ('Numeric', 'Numeric'), ('ReportingMonth', 'ReportingMonth'), ('Day', 'Day'), ('Duration', 'Duration'), ('Short', 'Short'), ('InclusiveValueRange', 'InclusiveValueRange'), ('KeyValues', 'KeyValues'), ('DataSetReference', 'DataSetReference'), ('BigInteger', 'BigInteger'), ('Month', 'Month'), ('Count', 'Count')], max_length=63)),
                ('is_sequence', models.NullBooleanField()),
                ('interval', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('start_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('end_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('time_interval', models.DurationField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('decimals', models.PositiveIntegerField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('is_multiLingual', models.NullBooleanField()),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='codelist',
            name='items',
        ),
        migrations.AddField(
            model_name='code',
            name='wrapper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='hydro_sdmx.Codelist', verbose_name='Codelist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codelist',
            name='id_code',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z][A-Za-z0-9_\\-]*', 32), 'Enter a value of type NCNameIDType that has pattern "([A-Za-z][A-Za-z0-9_\\-]*)"', 'invalid_pattern')], verbose_name='id'),
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_743458_idx'),
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_f3cf38_idx'),
        ),
        migrations.AddIndex(
            model_name='textformatinfo',
            index=models.Index(fields=['id_code', 'name'], name='hydro_sdmx__id_code_9ab18d_idx'),
        ),
        migrations.AddField(
            model_name='representation',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_representation_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='representation',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Codelist'),
        ),
        migrations.AddField(
            model_name='representation',
            name='enumeration_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='representation',
            name='text_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AddIndex(
            model_name='representation',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_f5b5af_idx'),
        ),
    ]
