# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0015_auto_20170925_1029'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='code',
            name='hydro_sdmx__name_9183d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='code',
            name='hydro_sdmx__id_code_655199_idx',
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('GregorianDay', 'GregorianDay'), ('DataSetReference', 'DataSetReference'), ('String', 'String'), (None, 'None'), ('Long', 'Long'), ('ReportingYear', 'ReportingYear'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Alpha', 'Alpha'), ('ReportingQuarter', 'ReportingQuarter'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Float', 'Float'), ('TimeRange', 'TimeRange'), ('Short', 'Short'), ('ReportingTrimester', 'ReportingTrimester'), ('Month', 'Month'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('MonthDay', 'MonthDay'), ('Numeric', 'Numeric'), ('URI', 'URI'), ('Boolean', 'Boolean'), ('AlphaNumeric', 'AlphaNumeric'), ('BasicTimePeriod', 'BasicTimePeriod'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Duration', 'Duration'), ('Count', 'Count'), ('DateTime', 'DateTime'), ('Decimal', 'Decimal'), ('ReportingSemester', 'ReportingSemester'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingWeek', 'ReportingWeek'), ('Double', 'Double'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingMonth', 'ReportingMonth'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('KeyValues', 'KeyValues'), ('Incremental', 'Incremental'), ('Day', 'Day'), ('Integer', 'Integer'), ('Time', 'Time'), ('XHTML', 'XHTML'), ('IdentifiableReference', 'IdentifiableReference'), ('GregorianYear', 'GregorianYear'), ('BigInteger', 'BigInteger')], max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('wrapper', 'id_code')]),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['wrapper'], name='hydro_sdmx__wrapper_bab4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['wrapper', 'id_code'], name='hydro_sdmx__wrapper_13e7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['wrapper', 'name'], name='hydro_sdmx__wrapper_d7ab86_idx'),
        ),
    ]
