# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0016_auto_20170925_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='id')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_concept_annotations_+', to='hydro_sdmx.Annotation')),
                ('iso_concept_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Concept')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Concept')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z][A-Za-z0-9_\\-]*', 32), 'Enter a value of type NCNameIDType that has pattern "([A-Za-z][A-Za-z0-9_\\-]*)"', 'invalid_pattern')], verbose_name='id')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_conceptscheme_annotations_+', to='hydro_sdmx.Annotation')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='representation',
            name='enumeration_format',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='text_format',
        ),
        migrations.AddField(
            model_name='textformatinfo',
            name='to_enumeration_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumeration_formats', to='hydro_sdmx.Representation'),
        ),
        migrations.AddField(
            model_name='textformatinfo',
            name='to_text_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_formats', to='hydro_sdmx.Representation'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='hydro_sdmx.Codelist'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Long', 'Long'), ('Double', 'Double'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('ReportingMonth', 'ReportingMonth'), ('TimeRange', 'TimeRange'), (None, 'None'), ('Integer', 'Integer'), ('AlphaNumeric', 'AlphaNumeric'), ('Count', 'Count'), ('DataSetReference', 'DataSetReference'), ('Float', 'Float'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Duration', 'Duration'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Month', 'Month'), ('Day', 'Day'), ('Alpha', 'Alpha'), ('KeyValues', 'KeyValues'), ('ReportingDay', 'ReportingDay'), ('XHTML', 'XHTML'), ('Numeric', 'Numeric'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Time', 'Time'), ('BigInteger', 'BigInteger'), ('IdentifiableReference', 'IdentifiableReference'), ('Decimal', 'Decimal'), ('String', 'String'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingWeek', 'ReportingWeek'), ('GregorianYear', 'GregorianYear'), ('GregorianDay', 'GregorianDay'), ('DateTime', 'DateTime'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ReportingYear', 'ReportingYear'), ('InclusiveValueRange', 'InclusiveValueRange'), ('MonthDay', 'MonthDay'), ('Boolean', 'Boolean'), ('Incremental', 'Incremental'), ('Short', 'Short'), ('URI', 'URI'), ('ReportingTrimester', 'ReportingTrimester')], max_length=63),
        ),
        migrations.AddField(
            model_name='concept',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Representation'),
        ),
        migrations.AddField(
            model_name='concept',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='hydro_sdmx.ConceptScheme', verbose_name='Concept Scheme'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_374a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_d963bf_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__b1799f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_875a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_9bcd2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptscheme',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_b3a8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['wrapper'], name='hydro_sdmx__wrapper_a75750_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['wrapper', 'id_code'], name='hydro_sdmx__wrapper_2a5973_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['wrapper', 'name'], name='hydro_sdmx__wrapper_7d24ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together=set([('wrapper', 'id_code')]),
        ),
    ]
