# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0017_auto_20170925_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textformatinfo',
            name='to_enumeration_format',
        ),
        migrations.RemoveField(
            model_name='textformatinfo',
            name='to_text_format',
        ),
        migrations.AddField(
            model_name='representation',
            name='enumeration_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AddField(
            model_name='representation',
            name='text_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.TextFormatInfo'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Codelist'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('String', 'String'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingSemester', 'ReportingSemester'), ('ReportingWeek', 'ReportingWeek'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Count', 'Count'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('KeyValues', 'KeyValues'), ('DataSetReference', 'DataSetReference'), ('ReportingDay', 'ReportingDay'), ('TimeRange', 'TimeRange'), ('URI', 'URI'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Integer', 'Integer'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('GregorianYear', 'GregorianYear'), ('Numeric', 'Numeric'), ('XHTML', 'XHTML'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('Boolean', 'Boolean'), ('Month', 'Month'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('MonthDay', 'MonthDay'), ('Long', 'Long'), ('Incremental', 'Incremental'), ('Day', 'Day'), ('Double', 'Double'), ('ReportingTrimester', 'ReportingTrimester'), ('Alpha', 'Alpha'), ('GregorianDay', 'GregorianDay'), ('BigInteger', 'BigInteger'), ('ReportingMonth', 'ReportingMonth'), ('ReportingYear', 'ReportingYear'), ('Duration', 'Duration'), ('DateTime', 'DateTime'), ('Time', 'Time'), ('Float', 'Float'), ('Decimal', 'Decimal'), ('Short', 'Short')], max_length=63),
        ),
    ]
