# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0018_auto_20170925_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Short', 'Short'), ('BigInteger', 'BigInteger'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('DateTime', 'DateTime'), ('MonthDay', 'MonthDay'), ('Decimal', 'Decimal'), ('ReportingSemester', 'ReportingSemester'), ('Time', 'Time'), ('KeyValues', 'KeyValues'), ('Double', 'Double'), ('ReportingMonth', 'ReportingMonth'), ('Boolean', 'Boolean'), ('InclusiveValueRange', 'InclusiveValueRange'), ('IdentifiableReference', 'IdentifiableReference'), ('Integer', 'Integer'), ('Alpha', 'Alpha'), ('XHTML', 'XHTML'), ('GregorianYear', 'GregorianYear'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingWeek', 'ReportingWeek'), ('TimeRange', 'TimeRange'), ('Month', 'Month'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Day', 'Day'), ('DataSetReference', 'DataSetReference'), ('Incremental', 'Incremental'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingDay', 'ReportingDay'), ('Duration', 'Duration'), ('Float', 'Float'), ('Count', 'Count'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('String', 'String'), ('AlphaNumeric', 'AlphaNumeric'), ('Numeric', 'Numeric'), ('Long', 'Long'), ('StandardTimePeriod', 'StandardTimePeriod'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ReportingYear', 'ReportingYear'), ('GregorianDay', 'GregorianDay'), ('URI', 'URI')], max_length=63),
        ),
    ]
