# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0019_auto_20170925_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_concept_role', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=True)),
                ('attached2measure', models.BooleanField(default=False)),
                ('annotations', models.ManyToManyField(blank=True, related_name='_attribute_annotations_+', to='hydro_sdmx.Annotation')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_dataflow_annotations_+', to='hydro_sdmx.Annotation')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_datastructure_annotations_+', to='hydro_sdmx.Annotation')),
                ('attribute_annotations', models.ManyToManyField(related_name='_datastructure_attribute_annotations_+', to='hydro_sdmx.Annotation')),
                ('attributes', models.ManyToManyField(related_name='_datastructure_attributes_+', through='hydro_sdmx.Attribute', to='hydro_sdmx.Concept')),
                ('dimension_annotations', models.ManyToManyField(related_name='_datastructure_dimension_annotations_+', to='hydro_sdmx.Annotation')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('dimension', 'Dimension'), ('time', 'TimeDimension'), ('measure', 'MeasureDimension')], max_length=15)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_concept_role', models.BooleanField(default=True)),
                ('annotations', models.ManyToManyField(blank=True, related_name='_dimension_annotations_+', to='hydro_sdmx.Annotation')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Concept')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_group_annotations_+', to='hydro_sdmx.Annotation')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='hydro_sdmx.DataStructure')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_obsvalue_annotations_+', to='hydro_sdmx.Annotation')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_for_obs_values', to='hydro_sdmx.Concept')),
                ('representation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_values', to='hydro_sdmx.Representation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('AlphaNumeric', 'AlphaNumeric'), ('TimeRange', 'TimeRange'), ('String', 'String'), ('Count', 'Count'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingYear', 'ReportingYear'), ('ReportingSemester', 'ReportingSemester'), ('DateTime', 'DateTime'), ('Integer', 'Integer'), ('Time', 'Time'), ('Duration', 'Duration'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('DataSetReference', 'DataSetReference'), (None, 'None'), ('Incremental', 'Incremental'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingDay', 'ReportingDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Boolean', 'Boolean'), ('ReportingWeek', 'ReportingWeek'), ('Double', 'Double'), ('GregorianDay', 'GregorianDay'), ('Decimal', 'Decimal'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Long', 'Long'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('Numeric', 'Numeric'), ('URI', 'URI'), ('ReportingMonth', 'ReportingMonth'), ('MonthDay', 'MonthDay'), ('GregorianYear', 'GregorianYear'), ('ReportingQuarter', 'ReportingQuarter'), ('Float', 'Float'), ('Day', 'Day'), ('Month', 'Month'), ('Short', 'Short'), ('Alpha', 'Alpha'), ('BigInteger', 'BigInteger')], max_length=63),
        ),
        migrations.AddField(
            model_name='dimension',
            name='groups',
            field=models.ManyToManyField(related_name='dimensions', to='hydro_sdmx.Group'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='measure_representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dimensions', to='hydro_sdmx.ConceptScheme'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='hydro_sdmx.Representation'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='roles',
            field=models.ManyToManyField(related_name='role_for_dimensions', to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataStructure', verbose_name='DSD'),
        ),
        migrations.AddField(
            model_name='datastructure',
            name='dimensions',
            field=models.ManyToManyField(related_name='dimensions', through='hydro_sdmx.Dimension', to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='datastructure',
            name='measure_annotations',
            field=models.ManyToManyField(related_name='_datastructure_measure_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='datastructure',
            name='obs_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.ObsValue'),
        ),
        migrations.AddField(
            model_name='datastructure',
            name='registrations',
            field=models.ManyToManyField(to='hydro_sdmx.MetaStructure'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataStructure'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attached2dim_in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_attributes2each_group_dim', to='hydro_sdmx.Group'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attached2dims',
            field=models.ManyToManyField(related_name='attached_attributes', to='hydro_sdmx.Dimension'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attached2groups',
            field=models.ManyToManyField(related_name='attached_attributes', to='hydro_sdmx.Group'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_for_attributes', to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='hydro_sdmx.Representation'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='roles',
            field=models.ManyToManyField(related_name='role_for_attributes', to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataStructure', verbose_name='DSD'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_d83833_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('id_code', 'structure')]),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_684670_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_2f738a_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_f44ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__534522_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_88699b_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_bf9ded_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datastructure',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='dataflow',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_b49685_idx'),
        ),
        migrations.AddIndex(
            model_name='dataflow',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_492fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='dataflow',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__d13657_idx'),
        ),
        migrations.AddIndex(
            model_name='dataflow',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_55a5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='dataflow',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_0567c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataflow',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_c08990_idx'),
        ),
    ]
