# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0020_auto_20170927_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('id_code', models.CharField(blank=True, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='obsvalue',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='obsvalue',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='obsvalue',
            name='representation',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attribute',
            name='hydro_sdmx__id_code_c08990_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimension',
            name='hydro_sdmx__id_code_684670_idx',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Concept'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.DataStructure', verbose_name='DSD'),
        ),
        migrations.RemoveField(
            model_name='datastructure',
            name='obs_value',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Concept'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='measure_representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.ConceptScheme'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Representation'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='roles',
            field=models.ManyToManyField(related_name='_dimension_roles_+', to='hydro_sdmx.Concept'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.DataStructure', verbose_name='DSD'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id_code',
            field=models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('ExclusiveValueRange', 'ExclusiveValueRange'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Count', 'Count'), ('TimeRange', 'TimeRange'), ('Month', 'Month'), ('ReportingSemester', 'ReportingSemester'), ('DataSetReference', 'DataSetReference'), ('Short', 'Short'), ('Time', 'Time'), ('Duration', 'Duration'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('GregorianDay', 'GregorianDay'), ('MonthDay', 'MonthDay'), ('Long', 'Long'), ('ReportingDay', 'ReportingDay'), (None, 'None'), ('Float', 'Float'), ('BigInteger', 'BigInteger'), ('Incremental', 'Incremental'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingWeek', 'ReportingWeek'), ('IdentifiableReference', 'IdentifiableReference'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Boolean', 'Boolean'), ('Numeric', 'Numeric'), ('DateTime', 'DateTime'), ('Day', 'Day'), ('Alpha', 'Alpha'), ('ReportingYear', 'ReportingYear'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('String', 'String'), ('ReportingMonth', 'ReportingMonth'), ('BasicTimePeriod', 'BasicTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Decimal', 'Decimal'), ('URI', 'URI'), ('XHTML', 'XHTML'), ('AlphaNumeric', 'AlphaNumeric'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('Double', 'Double'), ('GregorianYear', 'GregorianYear'), ('KeyValues', 'KeyValues'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Integer', 'Integer')], max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('id_code', 'concept', 'wrapper')]),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together=set([('id_code', 'concept', 'wrapper')]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='ObsValue',
        ),
        migrations.AddField(
            model_name='measure',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='_measure_annotations_+', to='hydro_sdmx.Annotation'),
        ),
        migrations.AddField(
            model_name='measure',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='measure',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.Representation'),
        ),
        migrations.AddField(
            model_name='measure',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hydro_sdmx.DataStructure', verbose_name='DSD'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='structure',
        ),
        migrations.AddField(
            model_name='datastructure',
            name='obs_value',
            field=models.ManyToManyField(related_name='_datastructure_obs_value_+', through='hydro_sdmx.Measure', to='hydro_sdmx.Concept'),
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together=set([('id_code', 'concept', 'wrapper')]),
        ),
    ]
