# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0021_auto_20171002_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvisionAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='URI')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]+(\\.[0-9]+)*', 32), 'Enter a value of type VersionType that has pattern "([0-9]+(\\.[0-9]+)*)"', 'invalid_pattern')])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('id_code', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$', 32), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation')),
                ('annotations', models.ManyToManyField(blank=True, related_name='_dataprovisionagreement_annotations_+', to='hydro_sdmx.Annotation')),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provision_agreements', to='hydro_sdmx.Organisation')),
                ('data_provider_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provision_agreements', to='hydro_sdmx.DataProviderScheme')),
                ('registrations', models.ManyToManyField(to='hydro_sdmx.MetaStructure')),
                ('structure_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_agreements', to='hydro_sdmx.Dataflow')),
            ],
            options={
                'ordering': ['id_code'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Count', 'Count'), ('Alpha', 'Alpha'), ('Integer', 'Integer'), ('Long', 'Long'), ('Decimal', 'Decimal'), ('URI', 'URI'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Boolean', 'Boolean'), ('GregorianYear', 'GregorianYear'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingSemester', 'ReportingSemester'), ('TimeRange', 'TimeRange'), ('IdentifiableReference', 'IdentifiableReference'), (None, 'None'), ('Duration', 'Duration'), ('ReportingMonth', 'ReportingMonth'), ('StandardTimePeriod', 'StandardTimePeriod'), ('ReportingDay', 'ReportingDay'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Float', 'Float'), ('XHTML', 'XHTML'), ('InclusiveValueRange', 'InclusiveValueRange'), ('GregorianDay', 'GregorianDay'), ('ReportingYear', 'ReportingYear'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('Month', 'Month'), ('Short', 'Short'), ('ReportingWeek', 'ReportingWeek'), ('DataSetReference', 'DataSetReference'), ('Time', 'Time'), ('AlphaNumeric', 'AlphaNumeric'), ('Double', 'Double'), ('KeyValues', 'KeyValues'), ('String', 'String'), ('BigInteger', 'BigInteger'), ('DateTime', 'DateTime'), ('Numeric', 'Numeric'), ('GregorianYearMonth', 'GregorianYearMonth'), ('Day', 'Day'), ('ReportingQuarter', 'ReportingQuarter'), ('MonthDay', 'MonthDay'), ('Incremental', 'Incremental')], max_length=63),
        ),
        migrations.AddIndex(
            model_name='dataprovisionagreement',
            index=models.Index(fields=['id_code'], name='hydro_sdmx__id_code_60c01d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprovisionagreement',
            index=models.Index(fields=['name'], name='hydro_sdmx__name_c72205_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprovisionagreement',
            index=models.Index(fields=['agency'], name='hydro_sdmx__agency__a1a9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprovisionagreement',
            index=models.Index(fields=['id_code', 'version'], name='hydro_sdmx__id_code_5c8bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprovisionagreement',
            index=models.Index(fields=['id_code', 'agency', 'version'], name='hydro_sdmx__id_code_8375a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataprovisionagreement',
            unique_together=set([('id_code', 'agency', 'version')]),
        ),
    ]
