# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0022_auto_20171002_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Month', 'Month'), (None, 'None'), ('String', 'String'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingDay', 'ReportingDay'), ('Time', 'Time'), ('Decimal', 'Decimal'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('KeyValues', 'KeyValues'), ('InclusiveValueRange', 'InclusiveValueRange'), ('DataSetReference', 'DataSetReference'), ('ReportingSemester', 'ReportingSemester'), ('ReportingWeek', 'ReportingWeek'), ('Day', 'Day'), ('BigInteger', 'BigInteger'), ('StandardTimePeriod', 'StandardTimePeriod'), ('GregorianDay', 'GregorianDay'), ('MonthDay', 'MonthDay'), ('Short', 'Short'), ('Integer', 'Integer'), ('GregorianYear', 'GregorianYear'), ('ReportingYear', 'ReportingYear'), ('URI', 'URI'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('Alpha', 'Alpha'), ('Double', 'Double'), ('Duration', 'Duration'), ('AlphaNumeric', 'AlphaNumeric'), ('Boolean', 'Boolean'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingMonth', 'ReportingMonth'), ('DateTime', 'DateTime'), ('TimeRange', 'TimeRange'), ('Float', 'Float'), ('XHTML', 'XHTML'), ('Long', 'Long'), ('Count', 'Count'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('Incremental', 'Incremental'), ('Numeric', 'Numeric')], max_length=63),
        ),
    ]
