# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0023_auto_20171002_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyscheme',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='code',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='codelist',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='conceptscheme',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='dataconsumerscheme',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='dataflow',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='dataproviderscheme',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='dataprovisionagreement',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='datastructure',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='group',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='organisationunitscheme',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='annotations',
        ),
        migrations.AddField(
            model_name='annotation',
            name='agencyscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.AgencyScheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Attribute'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Code'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='codelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Codelist'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Concept'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='conceptscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.ConceptScheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Contact'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataconsumerscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataConsumerScheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Dataflow'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataproviderscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataProviderScheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataprovisionagreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataProvisionAgreement'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='datastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.DataStructure'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Dimension'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Group'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Measure'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Organisation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='organisationunitscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.OrganisationUnitScheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_sdmx.Representation'),
        ),
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('Alpha', 'Alpha'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('MonthDay', 'MonthDay'), ('XHTML', 'XHTML'), ('ReportingYear', 'ReportingYear'), ('Month', 'Month'), ('AlphaNumeric', 'AlphaNumeric'), ('Boolean', 'Boolean'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('IdentifiableReference', 'IdentifiableReference'), ('GregorianYear', 'GregorianYear'), ('Time', 'Time'), ('Long', 'Long'), ('Integer', 'Integer'), ('BasicTimePeriod', 'BasicTimePeriod'), ('ReportingMonth', 'ReportingMonth'), ('TimeRange', 'TimeRange'), ('Day', 'Day'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('StandardTimePeriod', 'StandardTimePeriod'), ('DateTime', 'DateTime'), ('String', 'String'), ('ReportingSemester', 'ReportingSemester'), ('ReportingWeek', 'ReportingWeek'), ('Float', 'Float'), ('Duration', 'Duration'), ('Double', 'Double'), (None, 'None'), ('Numeric', 'Numeric'), ('Decimal', 'Decimal'), ('URI', 'URI'), ('Incremental', 'Incremental'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingTrimester', 'ReportingTrimester'), ('ReportingDay', 'ReportingDay'), ('KeyValues', 'KeyValues'), ('Short', 'Short'), ('DataSetReference', 'DataSetReference'), ('ReportingQuarter', 'ReportingQuarter'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('GregorianDay', 'GregorianDay'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Count', 'Count'), ('BigInteger', 'BigInteger')], max_length=63),
        ),
    ]
