# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0024_auto_20171003_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('StandardTimePeriod', 'StandardTimePeriod'), ('AlphaNumeric', 'AlphaNumeric'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('GregorianYear', 'GregorianYear'), ('ReportingTrimester', 'ReportingTrimester'), ('KeyValues', 'KeyValues'), ('Integer', 'Integer'), ('Count', 'Count'), ('GregorianYearMonth', 'GregorianYearMonth'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('ReportingWeek', 'ReportingWeek'), ('DateTime', 'DateTime'), ('Short', 'Short'), ('URI', 'URI'), ('Decimal', 'Decimal'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('ReportingQuarter', 'ReportingQuarter'), ('Time', 'Time'), ('ReportingDay', 'ReportingDay'), ('Alpha', 'Alpha'), ('BigInteger', 'BigInteger'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('MonthDay', 'MonthDay'), ('Day', 'Day'), ('DataSetReference', 'DataSetReference'), ('Month', 'Month'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('InclusiveValueRange', 'InclusiveValueRange'), ('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('Double', 'Double'), ('TimeRange', 'TimeRange'), ('BasicTimePeriod', 'BasicTimePeriod'), ('Duration', 'Duration'), ('Numeric', 'Numeric'), (None, 'None'), ('ReportingYear', 'ReportingYear'), ('ReportingSemester', 'ReportingSemester'), ('XHTML', 'XHTML'), ('String', 'String'), ('Incremental', 'Incremental'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('IdentifiableReference', 'IdentifiableReference'), ('Long', 'Long')], max_length=63),
        ),
    ]
