# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_sdmx', '0025_auto_20171003_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textformatinfo',
            name='text_type',
            field=models.CharField(blank=True, choices=[('ObservationalTimePeriod', 'ObservationalTimePeriod'), ('BasicTimePeriod', 'BasicTimePeriod'), ('String', 'String'), (None, 'None'), ('Alpha', 'Alpha'), ('Count', 'Count'), ('ReportingYear', 'ReportingYear'), ('TimeRange', 'TimeRange'), ('InclusiveValueRange', 'InclusiveValueRange'), ('Duration', 'Duration'), ('Time', 'Time'), ('IdentifiableReference', 'IdentifiableReference'), ('MonthDay', 'MonthDay'), ('DataSetReference', 'DataSetReference'), ('ExclusiveValueRange', 'ExclusiveValueRange'), ('Numeric', 'Numeric'), ('Incremental', 'Incremental'), ('GregorianYearMonth', 'GregorianYearMonth'), ('ReportingTimePeriod', 'ReportingTimePeriod'), ('ReportingWeek', 'ReportingWeek'), ('DateTime', 'DateTime'), ('XHTML', 'XHTML'), ('KeyValues', 'KeyValues'), ('Long', 'Long'), ('Integer', 'Integer'), ('ReportingTrimester', 'ReportingTrimester'), ('Month', 'Month'), ('AttachmentConstraintReference', 'AttachmentConstraintReference'), ('AlphaNumeric', 'AlphaNumeric'), ('ReportingSemester', 'ReportingSemester'), ('ReportingQuarter', 'ReportingQuarter'), ('ReportingDay', 'ReportingDay'), ('GregorianTimePeriod', 'GregorianTimePeriod'), ('URI', 'URI'), ('BigInteger', 'BigInteger'), ('Boolean', 'Boolean'), ('Float', 'Float'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('GregorianYear', 'GregorianYear'), ('GregorianDay', 'GregorianDay'), ('ReportingMonth', 'ReportingMonth'), ('Day', 'Day'), ('StandardTimePeriod', 'StandardTimePeriod'), ('Short', 'Short')], max_length=63),
        ),
    ]
